'use strict';
/* R.L ENERGIE — Toasts, fenêtres, vues (écrans) */
/* ---------- UI utilitaires ---------- */
function toast(m,k='ok'){const e=document.createElement('div');e.className='toast '+k;e.textContent=m;$('#toast').appendChild(e);setTimeout(()=>e.remove(),3500)}
let _pf=null;const dlg=(h,c='')=>{if(!$('#modal .dlg'))_pf=document.activeElement;$('#modal').innerHTML=`<div class="ov"><div class="dlg ${c}" role="dialog" aria-modal="true" tabindex="-1">${h}</div></div>`;const d=$('#modal .dlg');if(d)d.focus({preventScroll:true});const q=$('#pwi')||$('#pwn')||$('#cn');if(q)q.focus()},close=()=>{const f=_pf;_pf=null;$('#modal').innerHTML='';if(f&&f.isConnected&&f.focus)f.focus({preventScroll:true})};
const tryClose=()=>{const d=$('#modal .dlg');if(!d||pe||de||pl||d.classList.contains('danger'))return;close()};
const ask=(msg,fn)=>{pend=fn;dlg(`<h3>Confirmation</h3><p>${msg}</p><div class="row"><button class="btn ghost" data-a="close">Annuler</button><button class="btn ko" data-a="yes">Confirmer</button></div>`)};
function anchorDl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(a.href)},4000);toast('Fichier enregistré : '+name)}
let outF=null,outCb=null;
function dl(blob,name,cb){try{const f=new File([blob],name,{type:blob.type});if(navigator.canShare&&navigator.canShare({files:[f]})){outF=f;outCb=cb||null;return dlg(`<h3>Fichier prêt</h3><p style="word-break:break-all">${esc(name)} · ${fmtB(blob.size)}</p><div class="row"><button class="btn ok" data-a="fsave">💾 Enregistrer</button><button class="btn" data-a="fshare">📤 Partager / envoyer</button><button class="btn ghost" data-a="close">Fermer</button></div>`)}}catch(e){console.error(e)}anchorDl(blob,name);cb&&cb()}
const fname=r=>`Rapport_${r.client.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\W+/g,'_')}_${r.start.replace(/\//g,'-')}`;
const compress=(f,m=1280,q=.72)=>new Promise(res=>{const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{const k=Math.min(1,m/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res({d:c.toDataURL('image/jpeg',q),w:c.width,h:c.height})};im.onerror=()=>res(null);im.src=u});

/* ---------- Vues ---------- */
const info=c=>`<div class="info">${[['Adresse',c.address],['Puissance',c.power],['Contact',[c.contact,c.phone].filter(Boolean).join(' — ')],['Dernière maintenance',c.dates[0]],['Maintenances précédentes',c.dates.slice(1,4).join(' · ')],['Notes',c.notes]].filter(x=>x[1]).map(x=>`<div><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join('')}</div>`;
const histHTML=(q='')=>{q=q.toLowerCase();const L=reports.filter(r=>(r.client.name+' '+r.tech+' '+r.start).toLowerCase().includes(q));
return L.map(r=>{const s=stats(r);return `<div class="hi"><div class="hm"><b>${esc(r.client.name)}</b><span>${esc(r.start)} · ${esc(r.tech)}${r.mod?` · <i style="color:var(--nc);font-style:normal">modifié le ${esc(r.mod.date)}</i>`:''}</span><span class="pills"><i class="ok">${s.ok} conf.</i><i class="ko">${s.ko} déf.</i><i class="nc">${s.nc} N/C</i></span></div><div class="row">${perm('rep_exp')?[['pdf','PDF'],['xls','Excel'],['doc','Word']].map(f=>`<button class="btn sm" data-a="exp" data-f="${f[0]}" data-id="${r.id}">${f[1]}</button>`).join(''):''}${perm('rep_edit')?`<button class="btn sm ghost" data-a="redit" data-id="${r.id}">✎ Modifier</button>`:''}${perm('rep_del')?`<button class="btn sm ko" data-a="delrep" data-id="${r.id}">Suppr.</button>`:''}</div></div>`}).join('')||'<p style="color:var(--nc)">Aucun rapport enregistré.</p>'};

const PSEL=()=>{const L=procs.filter(p=>p.status==='pub');if(L.length<2)return'';const g={};L.forEach(p=>(g[p.cat||'Autres']=g[p.cat||'Autres']||[]).push(p));
const ks=Object.keys(g).sort((a,b)=>a==='Autres'?1:b==='Autres'?-1:a.localeCompare(b,'fr')),ord=ks.flatMap(k=>g[k]);if(!ord.some(p=>String(p.id)===String(form.pi)))form.pi=ord[0].id;
const o=p=>`<option value="${p.id}"${String(p.id)===String(form.pi)?' selected':''}>${esc(p.title)}</option>`;
return `<label>Procédure</label><select data-ch="proc">${ks.length>1?ks.map(k=>`<optgroup label="${esc(k)}">${g[k].map(o).join('')}</optgroup>`).join(''):ord.map(o).join('')}</select>`};
const dbtn=id=>{const d=docs.find(x=>x.id==id);return d?`<button class="btn sm ghost" data-a="vdoc" data-id="${d.id}">📄 ${esc(d.title)}</button>`:''};
const pDocs=()=>{const P=procs.find(x=>x.id===draft.pid);return P?P.docs||[]:draft.pdocs||[]};
const sDocs=(c,i)=>{const P=procs.find(x=>x.id===draft.pid),s=P&&P.steps[i]&&P.steps[i].t===c.t?P.steps[i]:c;return s.docs||[]};
const stepDocs=(c,i)=>{const g=i===0?pDocs().filter(x=>docs.some(d=>d.id===x)):[],l=sDocs(c,i).filter(x=>docs.some(d=>d.id===x));return(docs.length?`<div class="refs"><button class="btn sm ghost" data-a="wdocs">📚 Tous les documents (${docs.length})</button></div>`:'')+(g.length?`<div class="refs"><b>📚 Documents de référence</b>${g.map(dbtn).join('')}</div>`:'')+(l.length?`<div class="refs"><b>Documents pour cette étape</b>${l.map(dbtn).join('')}</div>`:'')};
const blobUrl=src=>{const[h,b]=src.split(','),bin=atob(b),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return URL.createObjectURL(new Blob([u],{type:h.match(/:(.*?);/)[1]}))};
const readDoc=async f=>{if(f.type==='application/pdf'){de.src=await new Promise(r=>{const x=new FileReader();x.onload=()=>r(x.result);x.readAsDataURL(f)});de.type='pdf'}else{const p=await compress(f,2000,.85);if(!p)return toast('Image illisible','err');de.src=p.d;de.type='image'}de.fn=f.name;if(!de.title)de.title=f.name.replace(/\.[^.]+$/,'')};
const admCo=()=>{const c=CO(),f=(k,l,ph='')=>`<div><label>${l}</label><input data-co="${k}" value="${esc(c[k])}" placeholder="${ph}"></div>`;return `<section class="card"><h2>Entreprise : page de garde des rapports</h2><div class="row2">${f('name','Nom')}${f('tag','Activité / slogan')}${f('addr','Adresse','N° et rue')}${f('zip','Code postal')}${f('city','Ville')}${f('tel','Téléphone')}${f('mail','E-mail')}${f('web','Site web')}${f('siret','SIRET')}</div><button class="btn ok" data-a="cosave" style="margin-top:1rem">Enregistrer</button></section>`};
const admDiag=()=>{const m=(navigator.userAgent.match(/Chrome\/[\d.]+/)||['inconnu'])[0];return `<section class="card"><h2>Diagnostic</h2><p><b>Version :</b> ${VER}<br><b>Espace utilisé :</b> <span id="stor">calcul…</span><br><b>Démarrages de l'app :</b> ${BOOT||'stockage indisponible'}<br><b>Stockage local :</b> ${STORE_OK?'✅ OK':'❌ non conservé'}<br><b>Adresse :</b> ${esc(location.protocol+'//'+(location.host||'(fichier)'))}<br><b>Moteur :</b> ${esc(m)}</p><p class="hint">Si « Démarrages » augmente tout seul pendant que tu n'utilises pas l'app, elle se recharge en boucle. Si le compteur reste à 1, le stockage n'est pas conservé.</p></section>`};
const admTabs=()=>[['c','Clients & données',perm('cli_edit')||perm('cli_del')||perm('backup')||perm('co_edit')||perm('diag')],['p','Procédures',perm('proc_edit')],['d','Documents',perm('doc_edit')],['k','Catégories',perm('proc_edit')||perm('doc_edit')],['s','Planning',perm('plan_add')||perm('plan_edit')||perm('plan_del')],['r','Droits & accès',admin]].filter(t=>t[2]);
const admRt=()=>{const R=rights();return `<section class="card"><h2>Droits et accès</h2><p class="sdesc">Deux profils : <b>Utilisateur</b> (le technicien, sans mot de passe) et <b>Administrateur</b> (mot de passe, tous les droits, non modifiable). Activez ce que l'utilisateur a le droit de faire : c'est appliqué tout de suite sur cette tablette.</p><div class="row"><button class="btn sm ghost" data-a="rpre" data-p="min">Restreint</button><button class="btn sm ghost" data-a="rpre" data-p="std">Standard (origine)</button><button class="btn sm ghost" data-a="rpre" data-p="all">Tout autoriser</button></div><p class="hint">Restreint : lancer une maintenance et exporter le rapport, rien d'autre. Un droit de gestion (clients, procédures, documents, données) fait apparaître le bouton Gestion chez l'utilisateur.</p></section>`+RIGHTS.map(g=>`<section class="card"><h2>${g[0]}</h2><div class="rt rth"><b>Droit</b><b>Utilisateur</b><b>Admin</b></div>${g[1].map(x=>`<label class="rt"><span>${x[1]}</span><input type="checkbox" class="tg" data-ch="rt" data-k="${x[0]}"${R[x[0]]?' checked':''}><span class="lock">✓ Toujours</span></label>`).join('')}</section>`).join('')+`<section class="card"><h2>Réservé à l'administrateur</h2><p class="sdesc">Ne peut pas être donné à l'utilisateur : cette page Droits et accès, le changement de mot de passe, le statut d'une intervention (terminée, annulée) et la modification du client, de la procédure ou du technicien d'une intervention déjà planifiée.</p><div class="row"><button class="btn ghost" data-a="pw">Changer le mot de passe</button></div></section>`};
const ADM=()=>{const T=admTabs();if(!T.some(t=>t[0]===admTab))admTab=T.length?T[0][0]:'c';
const body=admTab==='p'?admP():admTab==='d'?admD():admTab==='s'?admS():admTab==='k'?admK():admTab==='r'?admRt():(perm('co_edit')?admCo():'')+(perm('diag')?admDiag():'')+views.admC();
return (admin&&ls.get('rl_pw',null)===null?'<div class="warn">🔑 Le mot de passe administrateur par défaut (admin123) est toujours actif. Change-le dans Gestion > Droits & accès : « Changer le mot de passe ».</div>':'')+(admin?'':'<div class="hint">👤 Mode utilisateur : seules les fonctions autorisées par l\'administrateur sont disponibles.</div>')+`<div class="tabs">${T.map(t=>`<button class="tab${admTab===t[0]?' on':''}" data-a="tab" data-t="${t[0]}">${t[1]}</button>`).join('')}</div>`+body};
const grp=(k,L,row)=>{if(!L.length)return'';const cs=[...catList(k),''],m=cs.map(c=>{const l=L.filter(x=>(x.cat||'')===c);return l.length?`<h4 class="grp">${esc(c||'Sans catégorie')} <small>${l.length}</small></h4>`+l.map(row).join(''):''}).join('');return m};
const admP=()=>`<section class="card"><div class="split"><h2>Procédures (${procs.length})</h2><button class="btn ok" data-a="pedit" data-id="">+ Nouvelle procédure</button></div><p class="hint">Créez vos propres procédures : étapes, points de contrôle, documents et catégories.</p>${grp('p',procs,p=>`<div class="hi"><div class="hm"><b>${esc(p.title)}</b><span>v${p.ver} · ${p.steps.length} étapes · modifiée le ${esc(p.upd)}</span><span class="pills"><i class="${p.status==='pub'?'ok':'nc'}">${p.status==='pub'?'Publiée':'Brouillon'}</i></span></div><div class="row"><button class="btn sm" data-a="pedit" data-id="${p.id}">Modifier</button><button class="btn sm ghost" data-a="ppubt" data-id="${p.id}">${p.status==='pub'?'Masquer':'Publier'}</button><button class="btn sm ghost" data-a="pdup" data-id="${p.id}">Dupliquer</button><button class="btn sm ko" data-a="pdel" data-id="${p.id}">Suppr.</button></div></div>`)||'<p>Aucune procédure. Créez la première avec le bouton ci-dessus.</p>'}</section>`;
const admD=()=>`<section class="card"><div class="split"><h2>Documents (${docs.length})</h2><button class="btn ok" data-a="dedit" data-id="">+ Ajouter</button></div><p class="hint">Un document ajouté ici apparaît dans une procédure une fois attaché : cochez les procédures dans la fiche du document, ou une étape précise dans l'éditeur de procédure.</p>${grp('d',docs,d=>{const n=procs.filter(p=>(p.docs||[]).includes(d.id)||p.steps.some(s=>(s.docs||[]).includes(d.id))).length;return `<div class="hi"><div class="row" style="flex-wrap:nowrap">${d.type==='image'?`<img class="dth" src="${d.src}" alt="">`:'<span class="dth">📄</span>'}<div class="hm"><b>${esc(d.title)}</b><span>${n?`utilisé dans ${n} procédure(s)`:'<u>pas encore utilisé dans une procédure</u>'}</span><span>${esc(d.desc)}</span></div></div><div class="row"><button class="btn sm ghost" data-a="vdoc" data-id="${d.id}">Aperçu</button><button class="btn sm" data-a="dedit" data-id="${d.id}">Modifier / attacher</button><button class="btn sm ko" data-a="ddel" data-id="${d.id}">Suppr.</button></div></div>`})||'<p>Aucun document.</p>'}</section>`;
const admK=()=>['p','d'].filter(k=>perm(k==='p'?'proc_edit':'doc_edit')).map(k=>`<section class="card"><div class="split"><h2>Catégories de ${k==='p'?'procédures':'documents'}</h2><button class="btn ok" data-a="catnew" data-k="${k}">+ Nouvelle</button></div>${catList(k).map(c=>`<div class="hi"><div class="hm"><b>${esc(c)}</b><span>${catCount(k,c)} ${k==='p'?'procédure(s)':'document(s)'}</span></div><div class="row"><button class="btn sm" data-a="catren" data-k="${k}" data-n="${esc(c)}">Renommer</button><button class="btn sm ko" data-a="catdel" data-k="${k}" data-n="${esc(c)}">Suppr.</button></div></div>`).join('')||'<p>Aucune catégorie : créez-en une (ex : Onduleurs, Sécurité, Toiture…).</p>'}<p class="hint">Supprimer une catégorie ne supprime rien : ses éléments passent en « Sans catégorie ».</p></section>`).join('');
const dchk=(o,k)=>docs.length?docs.map(d=>`<label class="chk"><input type="checkbox" data-pc="docs"${k===undefined?'':` data-k="${k}"`} value="${d.id}"${(o.docs||[]).includes(d.id)?' checked':''}>${esc(d.title)}</label>`).join(''):'<small>Aucun document pour l\'instant.</small>';
const opt=(o,k,f,l)=>`<label class="chk"><input type="checkbox" data-pc="${f}" data-k="${k}"${o[f]?' checked':''}>${l}</label>`;
const catOpts=(k,cur)=>'<option value="">Sans catégorie</option>'+catList(k).map(c=>`<option${c===cur?' selected':''}>${esc(c)}</option>`).join('');
const peBadge=s=>[s.danger?'⚠ tension':'',s.torque?'🔧 couple':'',s.releve?'📊 relevé':'',(s.docs||[]).length?'📎 '+s.docs.length:''].filter(Boolean).join(' · ');
const peStep=(s,k,n)=>{const o=peOpen===k,pts=(s.i||[]);return `<div class="sed${o?' open':''}"><div class="split"><button class="sh" data-a="sopen" data-k="${k}"><b>${k+1}.</b> ${esc(s.t||'Étape sans titre')}<small>${pts.filter(x=>String(x).trim()).length} point(s) de contrôle${peBadge(s)?' · '+peBadge(s):''}</small></button><div class="row"><button class="btn sm ghost" data-a="smv" data-k="${k}" data-d="-1"${k?'':' disabled'}>↑</button><button class="btn sm ghost" data-a="smv" data-k="${k}" data-d="1"${k<n-1?'':' disabled'}>↓</button><button class="btn sm ghost" data-a="sdup" data-k="${k}">⧉</button><button class="btn sm ko" data-a="sdel" data-k="${k}">✕</button></div></div>${o?`<label>Titre de l'étape *</label><input data-pe="t" data-k="${k}" value="${esc(s.t)}" placeholder="Ex : Contrôle des câbles DC"><label>Consigne</label><textarea data-pe="desc" data-k="${k}" rows="2" placeholder="Ce que le technicien doit faire">${esc(s.desc)}</textarea><label>Avertissement</label><input data-pe="warn" data-k="${k}" value="${esc(s.warn)}" placeholder="Ex : Porter les gants isolants"><label>Points de contrôle (Conforme / Défaut / Non contrôlé)</label>${pts.map((x,j)=>`<div class="pt"><input data-pt="${j}" data-k="${k}" value="${esc(x)}" placeholder="Point à contrôler"><button class="btn sm ghost" data-a="ptdel" data-k="${k}" data-j="${j}" aria-label="Retirer ce point">✕</button></div>`).join('')}<button class="btn sm ghost" data-a="ptadd" data-k="${k}">+ Ajouter un point de contrôle</button><label>Options de l'étape</label><div class="chks">${opt(s,k,'danger','⚠ Sous tension')}${opt(s,k,'torque','🔧 Couple de serrage')}${opt(s,k,'releve','📊 Relevé compteurs')}</div><label>Documents proposés à cette étape</label><div class="chks">${dchk(s,k)}</div><button class="btn sm ghost" data-a="dnew" data-k="${k}" style="margin-top:.6rem">+ Créer un nouveau document</button>`:''}</div>`};
const peView=()=>{const p=pe;return `<section class="card"><div class="eyebrow">${p.isNew?'Création':'Modification'}</div><h2>${p.isNew?'Nouvelle procédure':'Modifier la procédure'}</h2><label>Titre *</label><input data-pe="title" value="${esc(p.title)}" placeholder="Ex : Maintenance onduleur"><label>Description</label><textarea data-pe="desc" rows="2">${esc(p.desc)}</textarea><div class="row2"><div><label>Catégorie</label><div class="row" style="flex-wrap:nowrap"><select data-pe="cat" style="flex:1">${catOpts('p',p.cat)}</select><button class="btn sm ghost" data-a="catnew" data-k="p" data-from="pe">+ Nouvelle</button></div></div><div><label>Statut</label><select data-pe="status"><option value="pub"${p.status==='pub'?' selected':''}>Publiée (visible par le technicien)</option><option value="draft"${p.status==='pub'?'':' selected'}>Brouillon (masquée)</option></select></div></div><label>📚 Documents de référence (proposés dès la 1re étape)</label><div class="chks">${dchk(p)}</div><button class="btn sm ghost" data-a="dnew" style="margin-top:.6rem">+ Créer un nouveau document</button></section><section class="card"><div class="split"><h2>Étapes (${p.steps.length})</h2><button class="btn ok sm" data-a="sadd">+ Ajouter une étape</button></div><p class="hint">Touchez une étape pour la modifier. ↑ ↓ pour l'ordre, ⧉ pour la dupliquer.</p>${p.steps.map((s,k)=>peStep(s,k,p.steps.length)).join('')}<button class="btn ghost big" data-a="sadd">+ Ajouter une étape</button></section>`};
const peR=()=>render();
const deHTML=()=>{const d=de;return `<h3>${d.isNew?'Nouveau document':'Modifier le document'}</h3><label>Titre *</label><input data-de="title" value="${esc(d.title)}"><label>Description</label><textarea data-de="desc" rows="2">${esc(d.desc)}</textarea><label>Catégorie</label><div class="row" style="flex-wrap:nowrap;margin:0"><select data-de="cat" style="flex:1">${catOpts('d',d.cat)}</select><button class="btn sm ghost" data-a="catnew" data-k="d" data-from="de">+ Nouvelle</button></div><label>Fichier (image ou PDF) *</label><label class="btn ghost file" style="margin:0">📎 ${d.src?'Remplacer le fichier':'Choisir un fichier'}<input type="file" accept="image/*,application/pdf" hidden data-ch="dfile"></label>${d.src?`<p class="hint">${d.type==='pdf'?'📄 PDF chargé':'🖼 Image chargée'}${d.fn?' : '+esc(d.fn):''}</p>${d.type==='image'?`<img class="dprev" src="${d.src}" alt="">`:''}`:''}${perm('proc_edit')&&procs.length&&deTarget===null?`<label>Utiliser dans les procédures</label><div class="chks">${procs.map(p=>`<label class="chk"><input type="checkbox" data-dp value="${p.id}"${(d.procs||[]).includes(String(p.id))?' checked':''}>${esc(p.title)}</label>`).join('')}</div><p class="hint">Le document est proposé au début de chaque procédure cochée. Pour une étape précise : éditeur de procédure.</p>`:''}<div class="row stick"><button class="btn ghost" data-a="dcancel">Annuler</button><button class="btn ok" data-a="dsave">Enregistrer</button></div>`};
const deR=()=>dlg(deHTML());
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.pt!==undefined&&pe){pe.steps[+t.dataset.k].i[+t.dataset.pt]=t.value;return}if(t.dataset.pe&&pe){const f=t.dataset.pe,o=t.dataset.k===undefined?pe:pe.steps[+t.dataset.k];f==='i'?o.i=t.value.split('\n').map(x=>x.trim()).filter(Boolean):o[f]=t.value}else if(t.dataset.de&&de)de[t.dataset.de]=t.value});
document.addEventListener('change',e=>{const t=e.target,f=t.dataset.pc;if(t.dataset.dp!==undefined&&de){de.procs=t.checked?[...(de.procs||[]),t.value]:(de.procs||[]).filter(x=>x!==t.value);return}if(!pe||f===undefined)return;const o=t.dataset.k===undefined?pe:pe.steps[+t.dataset.k];if(f==='docs')o.docs=t.checked?[...(o.docs||[]),t.value]:(o.docs||[]).filter(x=>x!==t.value);else o[f]=t.checked?1:0});

const lastBk=()=>+ls.get('rl_lastbk',0);
const daysSince=t=>t?Math.floor((Date.now()-t)/86400000):null;
const CO=()=>{const D={name:'R.L ENERGIE',tag:'Solaire photovoltaïque',addr:'6 Le Favril',zip:'28120',city:'Blandainville',tel:'02 37 81 36 11',mail:'contact@rl-energie.fr',web:'www.rl-energie.fr',siret:'840 910 541 00027'},S=ls.get('rl_co',{});if(ls.get('rl_co_v',0)<2){['addr','zip','city','tel','siret'].forEach(k=>delete S[k]);ls.set('rl_co',S);ls.set('rl_co_v',2)}return Object.fromEntries(Object.entries(D).map(([k,v])=>[k,S[k]||v]))};
const PP=()=>ls.get('rl_pp','both'),z2=x=>String(x).padStart(2,'0');
const nowKey=()=>{const n=new Date();return n.getFullYear()+'-'+z2(n.getMonth()+1)+'-'+z2(n.getDate())+' '+z2(n.getHours())+':'+z2(n.getMinutes())};
const fdate=d=>new Date(d+'T00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'});
const plSorted=()=>plans.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
const plRow=(p,a)=>{const c=clients.find(x=>x.id==p.clientId)||{name:'Client supprimé'},pr=procs.find(x=>x.id==p.procId),late=p.status==='planned'&&p.date+' '+p.time<nowKey(),st={planned:['Planifiée','nc'],done:['Terminée','ok'],cancelled:['Annulée','ko']}[p.status]||['Planifiée','nc'],can=perm('plan_edit')&&(p.status==='planned'||admin);
return `<div class="hi plr${late?' late':''}"><div class="pdt"><b>${fdate(p.date)}</b><span>${esc(p.time)}</span></div><div class="hm"><b>${esc(c.name)}</b><span>📍 ${esc(c.address||'Adresse non renseignée')}${c.address?` · <a href="${mapUrl(c.address)}" target="_blank" rel="noopener">Itinéraire</a>`:''}</span><span>${esc(pr?pr.title:'Procédure supprimée')}${p.tech?' · 👤 '+esc(p.tech):''}${c.phone?` · <a href="tel:${esc(c.phone)}">${esc(c.phone)}</a>`:''}</span>${p.notes?`<span>📝 ${esc(p.notes)}</span>`:''}<span class="pills"><i class="${late?'ko':st[1]}">${late?'En retard':st[0]}</i>${p.unplanned?'<i class="nc">Imprévue</i>':''}${p.hist&&p.hist.length?`<i class="nc">Reprogrammée ×${p.hist.length}</i>`:''}</span></div><div class="row">${p.status==='planned'?`<button class="btn sm ok" data-a="plgo" data-id="${p.id}">▶ Démarrer</button>`:''}${can?`<button class="btn sm ghost" data-a="pledit" data-id="${p.id}">🕒 ${admin?'Modifier':'Date / heure'}</button>`:''}${p.reportId&&reports.some(r=>r.id==p.reportId)&&perm('rep_exp')?`<button class="btn sm" data-a="exp" data-f="pdf" data-id="${p.reportId}">📄 Rapport</button>`:''}${a&&perm('plan_del')?`<button class="btn sm ko" data-a="pldel" data-id="${p.id}">Suppr.</button>`:''}</div></div>`};
let plh='up',plAll=0;
const plHome=()=>{const bad=STORE_OK?'':'<div class="warn">⚠ Le stockage de cet appareil n\'est pas conservé : les clients, rapports et plannings seront perdus à la fermeture. Voir Gestion, Diagnostic.</div>';const can=perm('plan_add'),L=plSorted().filter(p=>plh==='up'?p.status==='planned':p.status==='done');if(plh!=='up')L.reverse();const M=plAll?L:L.slice(0,8);const dj=daysSince(lastBk()),bk=dj===null?'<div class="warn">💾 Aucune sauvegarde n\'a encore été faite. Va dans Gestion pour en faire une.</div>':dj>=14?`<div class="warn">💾 Dernière sauvegarde il y a ${dj} jours. Pense à en refaire une dans Gestion.</div>`:'';
return bad+bk+`<section class="card"><div class="split"><h2>Interventions</h2>${can?'<button class="btn ok sm" data-a="pledit" data-id="">+ Planifier</button>':''}</div><div class="tabs">${[['up','À venir'],['old','Terminées']].map(t=>`<button class="tab${plh===t[0]?' on':''}" data-a="plhf" data-f="${t[0]}">${t[1]}</button>`).join('')}</div>${M.map(p=>plRow(p)).join('')||`<p style="color:var(--nc)">${plh==='up'?'Aucune intervention planifiée.':'Aucune intervention terminée.'}</p>`}${L.length>8?`<button class="btn sm ghost" data-a="plall" style="margin-top:.8rem">${plAll?'Réduire la liste':'Voir tout ('+L.length+')'}</button>`:''}</section>`};
const admS=()=>{const f=plf,L=plSorted().filter(p=>f==='all'||(f==='up'?p.status==='planned':p.status!=='planned'));return `<section class="card"><div class="split"><h2>Planning (${plans.length})</h2>${perm('plan_add')?'<button class="btn ok" data-a="pledit" data-id="">+ Planifier</button>':''}</div><div class="tabs">${[['up','À venir'],['old','Terminées / annulées'],['all','Tout']].map(t=>`<button class="tab${f===t[0]?' on':''}" data-a="plf" data-f="${t[0]}">${t[1]}</button>`).join('')}</div>${L.map(p=>plRow(p,1)).join('')||'<p>Aucune intervention.</p>'}</section>`};
const plHTML=()=>{const p=pl,a=admin||p.isNew,ad=admin;return `<h3>${p.isNew?'Planifier une intervention':(a?'Modifier l\'intervention':'Reprogrammer')}</h3>${a?`<label>Client *</label><select data-pl="clientId">${p.clientId?'':'<option value="">Choisir…</option>'}${clients.map(c=>`<option value="${c.id}"${c.id==p.clientId?' selected':''}>${esc(c.name)}</option>`).join('')}</select><label>Procédure *</label><select data-pl="procId">${procs.filter(x=>x.status==='pub'||x.id==p.procId).map(x=>`<option value="${x.id}"${x.id==p.procId?' selected':''}>${esc(x.title)}</option>`).join('')}</select>`:`<p class="sdesc"><b>${esc((clients.find(c=>c.id==p.clientId)||{}).name||'')}</b></p>`}<div class="row2"><div><label>Date *</label><input type="date" data-pl="date" value="${esc(p.date)}"></div><div><label>Heure *</label><input type="time" data-pl="time" value="${esc(p.time)}"></div></div>${a?`<label>Technicien</label><input data-pl="tech" list="techs2" value="${esc(p.tech)}" placeholder="Prénom Nom"><datalist id="techs2">${[...new Set([...reports.map(r=>r.tech),...plans.map(x=>x.tech)].filter(Boolean))].map(t=>`<option value="${esc(t)}">`).join('')}</datalist><label>Notes</label><textarea data-pl="notes" rows="2">${esc(p.notes)}</textarea>${ad?`<label>Statut</label><select data-pl="status">${[['planned','Planifiée'],['done','Terminée'],['cancelled','Annulée']].map(x=>`<option value="${x[0]}"${p.status===x[0]?' selected':''}>${x[1]}</option>`).join('')}</select>`:''}`:''}${p.isNew?'':`<label>Motif du changement (facultatif)</label><input data-pl="why" value="${esc(p.why||'')}" placeholder="Ex : client absent, météo…">`}${(p.hist||[]).length?`<h4 style="margin-top:1rem">Historique des changements</h4>${p.hist.slice(-5).map(h=>`<p class="hint">${esc(h.w)} — ${esc(h.by)} : ${esc(h.from)} → ${esc(h.to)}${h.why?' ('+esc(h.why)+')':''}</p>`).join('')}`:''}<div class="row stick"><button class="btn ghost" data-a="plcancel">Annuler</button><button class="btn ok" data-a="plsave">Enregistrer</button></div>`};
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.pl&&pl)pl[t.dataset.pl]=t.value});
const views={
home:()=>{const c=clients[form.ci],techs=[...new Set(reports.map(r=>r.tech))];
return `<div class="hero"><img class="herologo" data-logo alt="R.L ENERGIE"><div><h1>Tableau de bord</h1><p>${new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div class="kpi"><div><b>${clients.length}</b><span>Clients</span></div><div><b>${reports.length}</b><span>Rapports</span></div><div><b>${plans.filter(p=>p.status==='planned').length}</b><span>Planifiées</span></div></div></div>`+(drafts.length?`<section class="card"><h2>Maintenance${drafts.length>1?'s':''} en pause (${drafts.length})</h2>${drafts.map(d=>{const P=procs.find(x=>x.id===d.pid);return `<div class="hi"><div class="hm"><b>${esc(d.client.name)}</b><span>Étape ${d.step+1}/${d.steps.length} — ${esc(d.tech)}${P?' · '+esc(P.title):''}</span></div><div class="row"><button class="btn sm" data-a="resume" data-id="${d.id}">▶ Reprendre</button><button class="btn sm ghost ko" data-a="dropdraft" data-id="${d.id}">Abandonner</button></div></div>`}).join('')}</section>`:'')+
`${plHome()}<section class="card"><h2>Nouvelle maintenance</h2><label>Technicien</label><input data-in="tech" list="techs" value="${esc(form.tech)}" placeholder="Prénom Nom"><datalist id="techs">${techs.map(t=>`<option value="${esc(t)}">`).join('')}</datalist>
<label>Client / Installation</label><select data-ch="client"><option value="">Sélectionner un client…</option>${clients.map((x,i)=>`<option value="${i}"${String(i)===String(form.ci)?' selected':''}>${esc(x.name)}</option>`).join('')}</select>${c?info(c):''}${PSEL()}<button class="btn ok big" data-a="start">▶ Commencer la maintenance</button></section>
<section class="card"><h2>Documents de référence</h2><div class="tiles"><button class="tile" data-a="ref" data-d="et"><i>🏷</i><div>Étiquettes de sécurité<small>Schéma d'implantation</small></div></button><button class="tile" data-a="ref" data-d="tq"><i>🔧</i><div>Couples de serrage<small>Tableau par appareil</small></div></button></div></section>
<section class="card"><h2>Historique des rapports</h2><input data-in="q" placeholder="Rechercher un client, un technicien, une date…"><div id="hist">${histHTML()}</div></section>`},
adm:()=>ADM(),
pe:()=>peView(),
admC:()=>{const ce=perm('cli_edit'),cd=perm('cli_del'),bk=perm('backup');return (ce||cd?`<section class="card"><div class="split"><h2>Clients (${clients.length})</h2>${ce?'<button class="btn ok" data-a="cedit" data-id="">+ Nouveau client</button>':''}</div>${clients.map(c=>`<div class="hi"><div class="hm"><b>${esc(c.name)}</b><span>${esc([c.address,c.power].filter(Boolean).join(' · '))}</span><span>Dernière maintenance : ${esc(c.dates[0]||'—')}</span></div><div class="row">${ce?`<button class="btn sm" data-a="cedit" data-id="${c.id}">Modifier</button>`:''}${cd&&clients.length>1?`<button class="btn sm ghost" data-a="cmerge" data-id="${c.id}">Fusionner</button>`:''}${cd?`<button class="btn sm ko" data-a="cdel" data-id="${c.id}">Supprimer</button>`:''}</div></div>`).join('')||'<p>Aucun client.</p>'}</section>`:'')+(bk||admin?`<section class="card"><h2>Données et sécurité</h2><div class="row">${admin?'<button class="btn ghost" data-a="pw">Changer le mot de passe</button>':''}${bk?`<button class="btn ghost" data-a="bk">Sauvegarde complète</button><button class="btn ghost" data-a="bk" data-l="1">Sans photos (légère)</button><label class="btn ghost file" style="margin:0">Restaurer<input type="file" accept=".json" hidden data-ch="restore"></label>`:''}</div>${bk?'<p style="margin-top:1rem;color:var(--nc);font-size:.9rem">Les données sont stockées sur cette tablette. Faites une sauvegarde régulière. La sauvegarde « sans photos » est bien plus légère ; à la restauration, les rapports déjà présents gardent leurs photos.</p>':''}</section>`:'')},
wiz:()=>{const i=draft.step,c=STEPS[i],s=draft.steps[i];
return `${draft.editOf?'<div class="warn">✎ Modification d\'un rapport déjà terminé — les changements remplaceront le rapport existant.</div>':''}<div class="prog"><i style="width:${(i+1)/STEPS.length*100}%"></i></div><section class="card" style="margin-top:1rem"><div class="eyebrow">Étape ${i+1} / ${STEPS.length} · ${esc(draft.client.name)}</div><h2>${esc(c.t)}</h2>${c.desc?`<p class="sdesc">${esc(c.desc)}</p>`:''}${c.warn?`<div class="warn">⚠ ${esc(c.warn)}</div>`:''}${stepDocs(c,i)}
${c.danger?'<div class="warn">⚠ Travail sous tension — vérifiez les consignes de sécurité avant toute intervention.</div>':''}
${c.refs?`<div class="refs">${c.refs.map(d=>`<button class="btn sm ghost" data-a="ref" data-d="${d}">${d==='tq'?'🔧 Couples de serrage':'🏷 Étiquettes de sécurité'}</button>`).join('')}</div>`:''}
${c.i.length?`<div class="chk-head"><span>Points de contrôle</span><button class="btn sm ok" data-a="allok">✓ Tout conforme</button></div>${c.i.map((d,j)=>`<div class="line" data-j="${j}"><div>${esc(d)}</div><div class="seg">${['ok','ko','nc'].map(k=>`<button class="${k}${s.st[j]===k?' on':''}" data-a="st" data-j="${j}" data-k="${k}">${k==='nc'?'N/C':LBL[k]}</button>`).join('')}</div></div>`).join('')}`:''}
${c.torque?`<label>Couple de serrage appliqué</label><div class="row"><select id="tqs" data-ch="torque" style="flex:1"><option value="">— Choisir —</option>${TQ.map(t=>`<option${s.torque===t?' selected':''}>${t}</option>`).join('')}</select><input data-in="torque" value="${esc(s.torque)}" placeholder="ou valeur personnalisée" style="flex:1"></div>`:''}
${c.releve?`<label>Relevé compteur production (kWh)</label><input data-in="prod" inputmode="decimal" value="${esc(draft.prod)}" placeholder="Ex : 12456"><label>Relevé compteur non-consommation (kWh)</label><input data-in="conso" inputmode="decimal" value="${esc(draft.conso)}" placeholder="Ex : 8754">`:''}
<label>Observations${s.st.some(v=>v==='ko'||v==='nc')?' <span style="color:var(--ko)">— obligatoire ici</span>':''}</label><div class="chips">${(s.st.some(v=>v==='ko'||v==='nc')?['Poussière / encrassement','Corrosion légère','Câblage à resserrer','Bruit anormal','Échauffement constaté','Pièce à remplacer','À revoir à la prochaine visite']:['RAS — aucune anomalie','Nettoyage effectué','Point vérifié visuellement']).map(t=>`<button type="button" class="chip" data-a="chip" data-t="${esc(t)}">+ ${t}</button>`).join('')}</div><textarea data-in="obs" rows="4" placeholder="Notes, anomalies, commentaires…">${esc(s.obs)}</textarea>
<label>Photos</label><label class="btn ghost file" style="display:inline-flex">📷 Ajouter des photos<input type="file" accept="image/*" multiple hidden data-ch="photo"></label><div class="photos" id="ph">${phHTML()}</div></section>`},
done:()=>{const s=stats(last);return `<section class="card center"><div class="done">✅</div><h2>Maintenance enregistrée</h2><p>${esc(last.client.name)} — ${last.start}</p><div class="pills" style="margin:1rem 0"><i class="ok">${s.ok} conformes</i><i class="ko">${s.ko} défauts</i><i class="nc">${s.nc} non contrôlés</i></div>
<p style="color:var(--nc)">Le rapport est sauvegardé sur la tablette. ${perm('rep_exp')?'Exportez-le au format de votre choix :':'Un PDF a été enregistré automatiquement.'}</p><div class="row" style="justify-content:center;margin-top:1rem">${perm('rep_exp')?[['pdf','📄 PDF'],['xls','📊 Excel'],['doc','📝 Word (modifiable)']].map(f=>`<button class="btn" data-a="exp" data-f="${f[0]}" data-id="${last.id}">${f[1]}</button>`).join(''):''}</div><button class="btn ghost big" data-a="home">Retour à l'accueil</button></section>`}};
const phHTML=()=>draft.steps[draft.step].ph.map((p,k)=>`<div class="ph"><img src="${p.d}"><button data-a="phdel" data-k="${k}">×</button></div>`).join('');
let _vk='';
function render(){if(draft)use(draft);if((view==='adm'||view==='pe')&&!mgmt())view='home';if(view==='pe'&&!pe)view='adm';const ap=$('#app'),ay=ap?ap.scrollTop:0;const w=view==='wiz',last_=w&&draft.step===STEPS.length-1;
$('#app').innerHTML=`<header><div class="brand"><img class="logoimg" data-logo alt="R.L ENERGIE"><div><b>R.L <em>ENERGIE</em></b><small>Suivi de maintenance</small></div></div><nav>${admin?'<span class="badge">ADMIN</span>':''}${!w&&view!=='done'&&view!=='pe'?`${mgmt()?`<button class="btn hw" data-a="${view==='adm'?'home':'toadm'}">${view==='adm'?'Accueil':'Gestion'}</button>`:''}<button class="btn hw" data-a="admin">${admin?'Quitter admin':'🔒 Admin'}</button><button class="btn hn" data-a="menu" aria-haspopup="dialog">☰ Menu</button>`:''}</nav></header><main>${views[view]()}</main>${view==='pe'?`<div class="nav"><button class="btn ghost" data-a="pcancel">Annuler</button><span>${pe.steps.length} étape(s)</span><button class="btn ok" data-a="psave">✔ Enregistrer</button></div>`:''}${w?`<div class="nav"><button class="btn ghost" data-a="prev">← Précédent</button><span>${draft.step+1} / ${STEPS.length}</span><button class="btn ok" data-a="next">${last_?'✔ Terminer':'Suivant →'}</button></div>`:''}`;document.querySelectorAll('img[data-logo]').forEach(i=>{if(LOGO.d)i.src=LOGO.d});{const vk=view+(view==='wiz'&&draft?':'+draft.id+':'+draft.step:'')+(view==='adm'?':'+admTab:'')+(view==='pe'&&pe?':'+pe.id:'');if(ap)ap.scrollTop=vk===_vk?ay:0;_vk=vk}if(view==='adm')showStorage()}
const goStep=n=>{draft.step=n;saveDraft(1);render();scrollTo(0,0);if(STEPS[n].danger)dlg('<h3 style="color:var(--ko)">⚠ ATTENTION — TRAVAIL SOUS TENSION</h3><p>Vérifiez les consignes de sécurité avant toute intervention.</p><div class="row"><button class="btn ok" data-a="close">J\'ai vérifié — OK</button></div>','danger')};
