'use strict';
const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('fr-FR');
const ls={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{toast('Stockage plein','err')}}};
const hash=s=>{let a=0xdeadbeef,b=0x41c6ce57;for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);a=Math.imul(a^c,2654435761);b=Math.imul(b^c,1597334677)}a=Math.imul(a^a>>>16,2246822507)^Math.imul(b^b>>>13,3266489909);b=Math.imul(b^b>>>16,2246822507)^Math.imul(a^a>>>13,3266489909);return String(4294967296*(2097151&b)+(a>>>0))};
const idb=(()=>{let db;const open=()=>db||(db=new Promise((ok,ko)=>{const q=indexedDB.open('rl',1);q.onupgradeneeded=()=>q.result.createObjectStore('kv');q.onsuccess=()=>ok(q.result);q.onerror=()=>ko(q.error)}));
const tx=async(m,f)=>{const d=await open();return new Promise((ok,ko)=>{const t=d.transaction('kv',m),q=f(t.objectStore('kv'));t.oncomplete=()=>ok(q.result);t.onerror=()=>ko(t.error)})};
return{get:k=>tx('readonly',s=>s.get(k)),set:(k,v)=>tx('readwrite',s=>s.put(v,k)),del:k=>tx('readwrite',s=>s.delete(k))}})();

/* ---------- Référentiel des étapes ---------- */
const DEF=[
{t:'Drone thermique toiture',i:['Observation drone thermique']},
{t:'Caméra thermique onduleur AC + DC',i:['Observation thermique onduleur AC et DC']},
{t:'Ouverture du coffret AC et remise sous tension',i:['État visuel coffret AC'],danger:1,refs:['et']},
{t:'Vérification visuelle et nettoyage du local onduleur',i:['État visuel onduleurs','Câbles','Chemin de câble','Attache câble','Capot','Connectiques DC','Environnement','Étiquettes','Nettoyage','Test continuité'],refs:['et']},
{t:'Thermique coffret AC',i:['Observation thermique coffret AC']},
{t:'AGCP',i:['AGCP'],refs:['et']},
{t:'Vérification PDL',i:['Test différentiel','Paramétrage']},
{t:'Serrage PDL',i:['Coupure du sectionneur'],torque:1,refs:['tq']},
{t:'Vérification du couple de serrage',i:['Vérification couple de serrage'],torque:1,refs:['tq']},
{t:'Local onduleur',i:['Vérification couple de serrage base onduleur'],torque:1,refs:['tq']},
{t:'Ventilateur onduleur',i:['Nettoyage ventilateur onduleur']},
{t:'Remise en tension PDL + relevé de compteur',i:[],releve:1},
{t:'Vérification du redémarrage',i:['Vérification redémarrage']}];
let LOGO={d:window.LOGO_DATA,w:520,h:724},LOGOWM=window.LOGO_WM,plans=[],pl=null,plf='up',STEPS=DEF,procs=[],docs=[],admTab='c',pe=null,de=null;const use=r=>{STEPS=r&&r.def||DEF};
const TQ=['3,5 N.m','8 N.m','10 N.m','12 N.m','15 N.m','18 N.m','20 N.m','25 N.m','30 N.m','50 N.m'];
const TQREF=[['IC60N – C120N','ic60n',[['63 A à 125 A','3,5 N.m']]],['NSX100-400','nsx',[['100 / 160 / 250 A','15 N.m'],['400 A','50 N.m']]],['INS250-400','ins',[['250 A','15 N.m'],['400 A','50 N.m']]],['Épanouisseur 160-400','epanouisseur',[['160 / 250 A','15 N.m'],['400 / 630 A','50 N.m']]]];
const LBL={ok:'Conforme',ko:'Défaut',nc:'Non contrôlé',m:'Relevé','':'Non renseigné'};
const COL={ok:'1E8E3E',ko:'D93025',nc:'6B7683',m:'1D5FA8'},LIGHT={ok:'E3F4E8',ko:'FDE3E0',nc:'ECEFF3',m:'E1ECF8'};
const SEED=[{id:101,name:'Client A - 450 kWc',address:'Région PACA',power:'450 kWc',dates:['15/03/2025','10/09/2024']},{id:102,name:'Client B - 120 kWc',address:'Île-de-France',power:'120 kWc',dates:['08/01/2026','12/06/2025']},{id:103,name:'Client C - 800 kWc',address:'Occitanie',power:'800 kWc',dates:['22/11/2025','15/05/2025']}];
const norm=(c,k=0)=>({id:c.id||Date.now()+k,name:c.name||'Sans nom',address:c.address||'',power:c.power||'',contact:c.contact||'',phone:c.phone||'',notes:c.notes||c.details||'',dates:c.dates||c.oldDates||(c.lastMaint?[c.lastMaint]:[])});

/* ---------- État ---------- */
let clients=(ls.get('rl_clients',null)||SEED).map(norm),reports=[],draft=null,last=null,admin=false,view='home',editId=null,pend=null,form={tech:ls.get('rl_tech',''),ci:'',pi:''};
const saveClients=()=>ls.set('rl_clients',clients),saveReports=()=>idb.set('reports',reports),saveProcs=()=>idb.set('procs',procs),saveDocs=()=>idb.set('docs',docs),savePlans=()=>idb.set('plans',plans);
let tm;const saveDraft=(now)=>{clearTimeout(tm);const f=()=>draft&&idb.set('draft',draft);now?f():tm=setTimeout(f,300)};
const newDraft=(c,tech,P)=>(use({def:P.steps}),{def:P.steps,proc:P.title,pid:P.id,pdocs:P.docs||[],id:Date.now(),client:{...c},prev:c.dates[0]||'—',tech,start:today(),step:0,prod:'',conso:'',steps:STEPS.map(s=>({st:s.i.map(()=>''),obs:'',ph:[],torque:''}))});
const stats=r=>{use(r);const n={ok:0,ko:0,nc:0};STEPS.forEach((c,i)=>c.i.forEach((_,j)=>{const k=r.steps[i].st[j];if(k in n)n[k]++}));return n};
const lines=(r,i)=>{const c=STEPS[i],s=r.steps[i],o=c.i.map((d,j)=>({d,k:s.st[j]}));
if(c.torque&&s.torque)o.push({d:'Couple de serrage appliqué : '+s.torque,k:'m'});
if(c.releve){o.push({d:'Relevé compteur production : '+(r.prod||'—')+' kWh',k:'m'});o.push({d:'Relevé compteur non-consommation : '+(r.conso||'—')+' kWh',k:'m'})}return o};
const defects=r=>{const o=[];STEPS.forEach((c,i)=>c.i.forEach((x,j)=>r.steps[i].st[j]==='ko'&&o.push([`${i+1}. ${c.t}`,x,r.steps[i].obs||'—'])));return o};

/* ---------- UI utilitaires ---------- */
function toast(m,k='ok'){const e=document.createElement('div');e.className='toast '+k;e.textContent=m;$('#toast').appendChild(e);setTimeout(()=>e.remove(),3500)}
const dlg=(h,c='')=>{$('#modal').innerHTML=`<div class="ov"><div class="dlg ${c}">${h}</div></div>`},close=()=>{$('#modal').innerHTML=''};
const ask=(msg,fn)=>{pend=fn;dlg(`<h3>Confirmation</h3><p>${msg}</p><div class="row"><button class="btn ghost" data-a="close">Annuler</button><button class="btn ko" data-a="yes">Confirmer</button></div>`)};
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(a.href)},4000);toast('Fichier enregistré : '+name)}
const fname=r=>`Rapport_${r.client.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\W+/g,'_')}_${r.start.replace(/\//g,'-')}`;
const compress=(f,m=1280,q=.72)=>new Promise(res=>{const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{const k=Math.min(1,m/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res({d:c.toDataURL('image/jpeg',q),w:c.width,h:c.height})};im.onerror=()=>res(null);im.src=u});

/* ---------- Vues ---------- */
const info=c=>`<div class="info">${[['Adresse',c.address],['Puissance',c.power],['Contact',[c.contact,c.phone].filter(Boolean).join(' — ')],['Dernière maintenance',c.dates[0]],['Maintenances précédentes',c.dates.slice(1,4).join(' · ')],['Notes',c.notes]].filter(x=>x[1]).map(x=>`<div><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join('')}</div>`;
const histHTML=(q='')=>{q=q.toLowerCase();const L=reports.filter(r=>(r.client.name+' '+r.tech+' '+r.start).toLowerCase().includes(q));
return L.map(r=>{const s=stats(r);return `<div class="hi"><div class="hm"><b>${esc(r.client.name)}</b><span>${r.start} · ${esc(r.tech)}</span><span class="pills"><i class="ok">${s.ok} conf.</i><i class="ko">${s.ko} déf.</i><i class="nc">${s.nc} N/C</i></span></div><div class="row">${[['pdf','PDF'],['xls','Excel'],['doc','Word']].map(f=>`<button class="btn sm" data-a="exp" data-f="${f[0]}" data-id="${r.id}">${f[1]}</button>`).join('')}${admin?`<button class="btn sm ko" data-a="delrep" data-id="${r.id}">Suppr.</button>`:''}</div></div>`}).join('')||'<p style="color:var(--nc)">Aucun rapport enregistré.</p>'};

const PSEL=()=>{const L=procs.filter(p=>p.status==='pub');return L.length>1?`<label>Procédure</label><select data-ch="proc">${L.map(p=>`<option value="${p.id}"${String(p.id)===String(form.pi)?' selected':''}>${esc(p.title)}</option>`).join('')}</select>`:''};
const dbtn=id=>{const d=docs.find(x=>x.id==id);return d?`<button class="btn sm ghost" data-a="vdoc" data-id="${d.id}">📄 ${esc(d.title)}</button>`:''};
const stepDocs=(c,i)=>{const g=i===0?(draft.pdocs||[]):[],l=c.docs||[];return(g.length?`<div class="refs"><b>📚 Documents de référence</b>${g.map(dbtn).join('')}</div>`:'')+(l.length?`<div class="refs"><b>Documents pour cette étape</b>${l.map(dbtn).join('')}</div>`:'')};
const blobUrl=src=>{const[h,b]=src.split(','),bin=atob(b),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return URL.createObjectURL(new Blob([u],{type:h.match(/:(.*?);/)[1]}))};
const readDoc=async f=>{if(f.type==='application/pdf'){de.src=await new Promise(r=>{const x=new FileReader();x.onload=()=>r(x.result);x.readAsDataURL(f)});de.type='pdf'}else{const p=await compress(f,2000,.85);if(!p)return toast('Image illisible','err');de.src=p.d;de.type='image'}de.fn=f.name;if(!de.title)de.title=f.name.replace(/\.[^.]+$/,'')};
const admCo=()=>{const c=CO(),f=(k,l,ph='')=>`<div><label>${l}</label><input data-co="${k}" value="${esc(c[k])}" placeholder="${ph}"></div>`;return `<section class="card"><h2>Entreprise : page de garde des rapports</h2><div class="row2">${f('name','Nom')}${f('tag','Activité / slogan')}${f('addr','Adresse','N° et rue')}${f('zip','Code postal')}${f('city','Ville')}${f('tel','Téléphone')}${f('mail','E-mail')}${f('web','Site web')}${f('siret','SIRET')}</div><button class="btn ok" data-a="cosave" style="margin-top:1rem">Enregistrer</button></section>`};
const ADM=()=>`<div class="tabs">${[['c','Clients & données'],['p','Procédures'],['d','Documents'],['s','Planning']].map(t=>`<button class="tab${admTab===t[0]?' on':''}" data-a="tab" data-t="${t[0]}">${t[1]}</button>`).join('')}</div>`+(admTab==='p'?admP():admTab==='d'?admD():admTab==='s'?admS():admCo()+views.admC());
const admP=()=>`<section class="card"><div class="split"><h2>Procédures (${procs.length})</h2><button class="btn ok" data-a="pedit" data-id="">+ Nouvelle</button></div>${procs.map(p=>`<div class="hi"><div class="hm"><b>${esc(p.title)}</b><span>${esc(p.cat||'Sans catégorie')} · v${p.ver} · ${p.steps.length} étapes · modifiée le ${esc(p.upd)}</span><span class="pills"><i class="${p.status==='pub'?'ok':'nc'}">${p.status==='pub'?'Publiée':'Brouillon'}</i></span></div><div class="row"><button class="btn sm" data-a="pedit" data-id="${p.id}">Modifier</button><button class="btn sm ghost" data-a="pdup" data-id="${p.id}">Dupliquer</button><button class="btn sm ko" data-a="pdel" data-id="${p.id}">Suppr.</button></div></div>`).join('')||'<p>Aucune procédure.</p>'}</section>`;
const admD=()=>`<section class="card"><div class="split"><h2>Documents (${docs.length})</h2><button class="btn ok" data-a="dedit" data-id="">+ Ajouter</button></div>${docs.map(d=>{const n=procs.filter(p=>(p.docs||[]).includes(d.id)||p.steps.some(s=>(s.docs||[]).includes(d.id))).length;return `<div class="hi"><div class="row" style="flex-wrap:nowrap">${d.type==='image'?`<img class="dth" src="${d.src}" alt="">`:'<span class="dth">📄</span>'}<div class="hm"><b>${esc(d.title)}</b><span>${esc(d.cat||'Non classé')} · utilisé dans ${n} procédure(s)</span><span>${esc(d.desc)}</span></div></div><div class="row"><button class="btn sm ghost" data-a="vdoc" data-id="${d.id}">Aperçu</button><button class="btn sm" data-a="dedit" data-id="${d.id}">Modifier / remplacer</button><button class="btn sm ko" data-a="ddel" data-id="${d.id}">Suppr.</button></div></div>`}).join('')||'<p>Aucun document.</p>'}</section>`;
const dchk=(o,k)=>docs.length?docs.map(d=>`<label class="chk"><input type="checkbox" data-pc="docs"${k===undefined?'':` data-k="${k}"`} value="${d.id}"${(o.docs||[]).includes(d.id)?' checked':''}>${esc(d.title)}</label>`).join(''):'<small>Aucun document : ajoutez-en dans l\'onglet Documents.</small>';
const opt=(o,k,f,l)=>`<label class="chk"><input type="checkbox" data-pc="${f}" data-k="${k}"${o[f]?' checked':''}>${l}</label>`;
const peHTML=()=>{const p=pe;return `<h3>${p.isNew?'Nouvelle procédure':'Modifier la procédure'}</h3><label>Titre *</label><input data-pe="title" value="${esc(p.title)}"><label>Description</label><textarea data-pe="desc" rows="2">${esc(p.desc)}</textarea><div class="row2"><div><label>Catégorie</label><input data-pe="cat" list="cats" value="${esc(p.cat)}"><datalist id="cats">${[...new Set(procs.map(x=>x.cat).filter(Boolean))].map(c=>`<option value="${esc(c)}">`).join('')}</datalist></div><div><label>Statut</label><select data-pe="status"><option value="pub"${p.status==='pub'?' selected':''}>Publiée</option><option value="draft"${p.status==='pub'?'':' selected'}>Brouillon (masquée)</option></select></div></div><label>📚 Documents de référence (début de procédure)</label><div class="chks">${dchk(p)}</div><h4 style="margin-top:1.2rem">Étapes (${p.steps.length})</h4>${p.steps.map((s,k)=>`<div class="sed"><div class="split"><b>Étape ${k+1}</b><div class="row"><button class="btn sm ghost" data-a="smv" data-k="${k}" data-d="-1">↑</button><button class="btn sm ghost" data-a="smv" data-k="${k}" data-d="1">↓</button><button class="btn sm ko" data-a="sdel" data-k="${k}">✕</button></div></div><label>Titre</label><input data-pe="t" data-k="${k}" value="${esc(s.t)}"><label>Consigne</label><textarea data-pe="desc" data-k="${k}" rows="2">${esc(s.desc)}</textarea><label>Avertissement</label><input data-pe="warn" data-k="${k}" value="${esc(s.warn)}"><label>Points de contrôle (un par ligne)</label><textarea data-pe="i" data-k="${k}" rows="3">${esc((s.i||[]).join('\n'))}</textarea><div class="chks" style="margin-top:.6rem">${opt(s,k,'danger','⚠ Sous tension')}${opt(s,k,'torque','🔧 Couple de serrage')}${opt(s,k,'releve','📊 Relevé compteurs')}</div><label>Documents proposés à cette étape</label><div class="chks">${dchk(s,k)}</div></div>`).join('')}<button class="btn sm" data-a="sadd">+ Ajouter une étape</button><div class="row stick"><button class="btn ghost" data-a="pcancel">Annuler</button><button class="btn ok" data-a="psave">Enregistrer</button></div>`};
const peR=()=>{const o=$('#modal .dlg'),y=o?o.scrollTop:0;dlg(peHTML(),'wide');const n=$('#modal .dlg');if(n)n.scrollTop=y};
const deHTML=()=>{const d=de;return `<h3>${d.isNew?'Nouveau document':'Modifier le document'}</h3><label>Titre *</label><input data-de="title" value="${esc(d.title)}"><label>Description</label><textarea data-de="desc" rows="2">${esc(d.desc)}</textarea><label>Classement</label><input data-de="cat" list="dcats" value="${esc(d.cat)}"><datalist id="dcats">${[...new Set(docs.map(x=>x.cat).filter(Boolean))].map(c=>`<option value="${esc(c)}">`).join('')}</datalist><label>Fichier (image ou PDF) *</label><label class="btn ghost file" style="margin:0">📎 ${d.src?'Remplacer le fichier':'Choisir un fichier'}<input type="file" accept="image/*,application/pdf" hidden data-ch="dfile"></label>${d.src?`<p class="hint">${d.type==='pdf'?'📄 PDF chargé':'🖼 Image chargée'}${d.fn?' : '+esc(d.fn):''}</p>${d.type==='image'?`<img class="dprev" src="${d.src}" alt="">`:''}`:''}<div class="row stick"><button class="btn ghost" data-a="dcancel">Annuler</button><button class="btn ok" data-a="dsave">Enregistrer</button></div>`};
const deR=()=>dlg(deHTML());
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.pe&&pe){const f=t.dataset.pe,o=t.dataset.k===undefined?pe:pe.steps[+t.dataset.k];f==='i'?o.i=t.value.split('\n').map(x=>x.trim()).filter(Boolean):o[f]=t.value}else if(t.dataset.de&&de)de[t.dataset.de]=t.value});
document.addEventListener('change',e=>{const t=e.target,f=t.dataset.pc;if(!pe||f===undefined)return;const o=t.dataset.k===undefined?pe:pe.steps[+t.dataset.k];if(f==='docs')o.docs=t.checked?[...(o.docs||[]),t.value]:(o.docs||[]).filter(x=>x!==t.value);else o[f]=t.checked?1:0});

const CO=()=>{const D={name:'R.L ENERGIE',tag:'Solaire photovoltaïque',addr:'6 Le Favril',zip:'28120',city:'Blandainville',tel:'02 37 81 36 11',mail:'contact@rl-energie.fr',web:'www.rl-energie.fr',siret:'840 910 541 00027'},S=ls.get('rl_co',{});if(ls.get('rl_co_v',0)<2){['addr','zip','city','tel','siret'].forEach(k=>delete S[k]);ls.set('rl_co',S);ls.set('rl_co_v',2)}return Object.fromEntries(Object.entries(D).map(([k,v])=>[k,S[k]||v]))};
const PP=()=>ls.get('rl_pp','both'),z2=x=>String(x).padStart(2,'0');
const nowKey=()=>{const n=new Date();return n.getFullYear()+'-'+z2(n.getMonth()+1)+'-'+z2(n.getDate())+' '+z2(n.getHours())+':'+z2(n.getMinutes())};
const fdate=d=>new Date(d+'T00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'});
const plSorted=()=>plans.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
const plRow=(p,a)=>{const c=clients.find(x=>x.id==p.clientId)||{name:'Client supprimé'},pr=procs.find(x=>x.id==p.procId),late=p.status==='planned'&&p.date+' '+p.time<nowKey(),st={planned:['Planifiée','nc'],done:['Terminée','ok'],cancelled:['Annulée','ko']}[p.status]||['Planifiée','nc'],can=(admin||PP()==='both')&&(p.status==='planned'||admin);
return `<div class="hi plr${late?' late':''}"><div class="pdt"><b>${fdate(p.date)}</b><span>${esc(p.time)}</span></div><div class="hm"><b>${esc(c.name)}</b><span>📍 ${esc(c.address||'Adresse non renseignée')}${c.address?` · <a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.address)}" target="_blank" rel="noopener">Itinéraire</a>`:''}</span><span>${esc(pr?pr.title:'Procédure supprimée')}${p.tech?' · 👤 '+esc(p.tech):''}${c.phone?` · <a href="tel:${esc(c.phone)}">${esc(c.phone)}</a>`:''}</span>${p.notes?`<span>📝 ${esc(p.notes)}</span>`:''}<span class="pills"><i class="${late?'ko':st[1]}">${late?'En retard':st[0]}</i>${p.unplanned?'<i class="nc">Imprévue</i>':''}${p.hist&&p.hist.length?`<i class="nc">Reprogrammée ×${p.hist.length}</i>`:''}</span></div><div class="row">${p.status==='planned'?`<button class="btn sm ok" data-a="plgo" data-id="${p.id}">▶ Démarrer</button>`:''}${can?`<button class="btn sm ghost" data-a="pledit" data-id="${p.id}">🕒 ${admin?'Modifier':'Date / heure'}</button>`:''}${p.reportId?`<button class="btn sm" data-a="exp" data-f="pdf" data-id="${p.reportId}">📄 Rapport</button>`:''}${a&&admin?`<button class="btn sm ko" data-a="pldel" data-id="${p.id}">Suppr.</button>`:''}</div></div>`};
let plh='up';
const plHome=()=>{const can=admin||PP()==='both',L=plSorted().filter(p=>plh==='up'?p.status==='planned':p.status==='done');if(plh!=='up')L.reverse();const M=L.slice(0,8);return `<section class="card"><div class="split"><h2>Interventions</h2>${can?'<button class="btn ok sm" data-a="pledit" data-id="">+ Planifier</button>':''}</div><div class="tabs">${[['up','À venir'],['old','Terminées']].map(t=>`<button class="tab${plh===t[0]?' on':''}" data-a="plhf" data-f="${t[0]}">${t[1]}</button>`).join('')}</div>${M.map(p=>plRow(p)).join('')||`<p style="color:var(--nc)">${plh==='up'?'Aucune intervention planifiée.':'Aucune intervention terminée.'}</p>`}</section>`};
const admS=()=>{const f=plf,L=plSorted().filter(p=>f==='all'||(f==='up'?p.status==='planned':p.status!=='planned'));return `<section class="card"><div class="split"><h2>Planning (${plans.length})</h2><button class="btn ok" data-a="pledit" data-id="">+ Planifier</button></div><label>Qui peut modifier les dates et heures</label><select data-ch="pp"><option value="admin"${PP()==='admin'?' selected':''}>Administrateur seulement</option><option value="both"${PP()==='both'?' selected':''}>Administrateur + techniciens (reprogrammer)</option></select><div class="tabs" style="margin-top:1rem">${[['up','À venir'],['old','Terminées / annulées'],['all','Tout']].map(t=>`<button class="tab${f===t[0]?' on':''}" data-a="plf" data-f="${t[0]}">${t[1]}</button>`).join('')}</div>${L.map(p=>plRow(p,1)).join('')||'<p>Aucune intervention.</p>'}</section>`};
const plHTML=()=>{const p=pl,a=admin||p.isNew,ad=admin;return `<h3>${p.isNew?'Planifier une intervention':(a?'Modifier l\'intervention':'Reprogrammer')}</h3>${a?`<label>Client *</label><select data-pl="clientId">${p.clientId?'':'<option value="">Choisir…</option>'}${clients.map(c=>`<option value="${c.id}"${c.id==p.clientId?' selected':''}>${esc(c.name)}</option>`).join('')}</select><label>Procédure *</label><select data-pl="procId">${procs.filter(x=>x.status==='pub'||x.id==p.procId).map(x=>`<option value="${x.id}"${x.id==p.procId?' selected':''}>${esc(x.title)}</option>`).join('')}</select>`:`<p class="sdesc"><b>${esc((clients.find(c=>c.id==p.clientId)||{}).name||'')}</b></p>`}<div class="row2"><div><label>Date *</label><input type="date" data-pl="date" value="${esc(p.date)}"></div><div><label>Heure *</label><input type="time" data-pl="time" value="${esc(p.time)}"></div></div>${a?`<label>Technicien</label><input data-pl="tech" list="techs2" value="${esc(p.tech)}" placeholder="Prénom Nom"><datalist id="techs2">${[...new Set([...reports.map(r=>r.tech),...plans.map(x=>x.tech)].filter(Boolean))].map(t=>`<option value="${esc(t)}">`).join('')}</datalist><label>Notes</label><textarea data-pl="notes" rows="2">${esc(p.notes)}</textarea>${ad?`<label>Statut</label><select data-pl="status">${[['planned','Planifiée'],['done','Terminée'],['cancelled','Annulée']].map(x=>`<option value="${x[0]}"${p.status===x[0]?' selected':''}>${x[1]}</option>`).join('')}</select>`:''}`:''}${p.isNew?'':`<label>Motif du changement (facultatif)</label><input data-pl="why" value="${esc(p.why||'')}" placeholder="Ex : client absent, météo…">`}${(p.hist||[]).length?`<h4 style="margin-top:1rem">Historique des changements</h4>${p.hist.slice(-5).map(h=>`<p class="hint">${esc(h.w)} — ${esc(h.by)} : ${esc(h.from)} → ${esc(h.to)}${h.why?' ('+esc(h.why)+')':''}</p>`).join('')}`:''}<div class="row stick"><button class="btn ghost" data-a="plcancel">Annuler</button><button class="btn ok" data-a="plsave">Enregistrer</button></div>`};
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.pl&&pl)pl[t.dataset.pl]=t.value});
const views={
home:()=>{const c=clients[form.ci],techs=[...new Set(reports.map(r=>r.tech))];
return `<div class="hero"><img class="herologo" src="logo.png" alt="R.L ENERGIE"><div><h1>Tableau de bord</h1><p>${new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div class="kpi"><div><b>${clients.length}</b><span>Clients</span></div><div><b>${reports.length}</b><span>Rapports</span></div><div><b>${plans.filter(p=>p.status==='planned').length}</b><span>Planifiées</span></div></div></div>`+(draft?`<div class="card resume"><div><b>Maintenance en cours</b><br><span>${esc(draft.client.name)} — étape ${draft.step+1}/${STEPS.length} — ${esc(draft.tech)}</span></div><div class="row"><button class="btn" data-a="resume">Reprendre</button><button class="btn ghost" data-a="dropdraft">Abandonner</button></div></div>`:'')+
`${plHome()}<section class="card"><h2>Nouvelle maintenance</h2><label>Technicien</label><input data-in="tech" list="techs" value="${esc(form.tech)}" placeholder="Prénom Nom"><datalist id="techs">${techs.map(t=>`<option value="${esc(t)}">`).join('')}</datalist>
<label>Client / Installation</label><select data-ch="client"><option value="">Sélectionner un client…</option>${clients.map((x,i)=>`<option value="${i}"${String(i)===String(form.ci)?' selected':''}>${esc(x.name)}</option>`).join('')}</select>${c?info(c):''}${PSEL()}<button class="btn ok big" data-a="start">▶ Commencer la maintenance</button></section>
<section class="card"><h2>Documents de référence</h2><div class="tiles"><button class="tile" data-a="ref" data-d="et"><i>🏷</i><div>Étiquettes de sécurité<small>Schéma d'implantation</small></div></button><button class="tile" data-a="ref" data-d="tq"><i>🔧</i><div>Couples de serrage<small>Tableau par appareil</small></div></button></div></section>
<section class="card"><h2>Historique des rapports</h2><input data-in="q" placeholder="Rechercher un client, un technicien, une date…"><div id="hist">${histHTML()}</div></section>`},
adm:()=>ADM(),
admC:()=>`<section class="card"><div class="split"><h2>Clients (${clients.length})</h2><button class="btn ok" data-a="cedit" data-id="">+ Nouveau client</button></div>${clients.map(c=>`<div class="hi"><div class="hm"><b>${esc(c.name)}</b><span>${esc([c.address,c.power].filter(Boolean).join(' · '))}</span><span>Dernière maintenance : ${esc(c.dates[0]||'—')}</span></div><div class="row"><button class="btn sm" data-a="cedit" data-id="${c.id}">Modifier</button><button class="btn sm ko" data-a="cdel" data-id="${c.id}">Supprimer</button></div></div>`).join('')||'<p>Aucun client.</p>'}</section>
<section class="card"><h2>Données et sécurité</h2><div class="row"><button class="btn ghost" data-a="pw">Changer le mot de passe</button><button class="btn ghost" data-a="bk">Sauvegarde (JSON)</button><label class="btn ghost file" style="margin:0">Restaurer<input type="file" accept=".json" hidden data-ch="restore"></label></div><p style="margin-top:1rem;color:var(--nc);font-size:.9rem">Les données sont stockées sur cette tablette. Faites une sauvegarde régulière.</p></section>`,
wiz:()=>{const i=draft.step,c=STEPS[i],s=draft.steps[i];
return `<div class="prog"><i style="width:${(i+1)/STEPS.length*100}%"></i></div><section class="card" style="margin-top:1rem"><div class="eyebrow">Étape ${i+1} / ${STEPS.length} · ${esc(draft.client.name)}</div><h2>${c.t}</h2>${c.desc?`<p class="sdesc">${esc(c.desc)}</p>`:''}${c.warn?`<div class="warn">⚠ ${esc(c.warn)}</div>`:''}${stepDocs(c,i)}
${c.danger?'<div class="warn">⚠ Travail sous tension — vérifiez les consignes de sécurité avant toute intervention.</div>':''}
${c.refs?`<div class="refs">${c.refs.map(d=>`<button class="btn sm ghost" data-a="ref" data-d="${d}">${d==='tq'?'🔧 Couples de serrage':'🏷 Étiquettes de sécurité'}</button>`).join('')}</div>`:''}
${c.i.length?`<div class="chk-head"><span>Points de contrôle</span><button class="btn sm ok" data-a="allok">✓ Tout conforme</button></div>${c.i.map((d,j)=>`<div class="line" data-j="${j}"><div>${d}</div><div class="seg">${['ok','ko','nc'].map(k=>`<button class="${k}${s.st[j]===k?' on':''}" data-a="st" data-j="${j}" data-k="${k}">${k==='nc'?'N/C':LBL[k]}</button>`).join('')}</div></div>`).join('')}`:''}
${c.torque?`<label>Couple de serrage appliqué</label><div class="row"><select id="tqs" data-ch="torque" style="flex:1"><option value="">— Choisir —</option>${TQ.map(t=>`<option${s.torque===t?' selected':''}>${t}</option>`).join('')}</select><input data-in="torque" value="${esc(s.torque)}" placeholder="ou valeur personnalisée" style="flex:1"></div>`:''}
${c.releve?`<label>Relevé compteur production (kWh)</label><input data-in="prod" inputmode="decimal" value="${esc(draft.prod)}" placeholder="Ex : 12456"><label>Relevé compteur non-consommation (kWh)</label><input data-in="conso" inputmode="decimal" value="${esc(draft.conso)}" placeholder="Ex : 8754">`:''}
<label>Observations</label><textarea data-in="obs" rows="4" placeholder="Notes, anomalies, commentaires…">${esc(s.obs)}</textarea>
<label>Photos</label><label class="btn ghost file" style="display:inline-flex">📷 Ajouter des photos<input type="file" accept="image/*" multiple hidden data-ch="photo"></label><div class="photos" id="ph">${phHTML()}</div></section>`},
done:()=>{const s=stats(last);return `<section class="card center"><div class="done">✅</div><h2>Maintenance enregistrée</h2><p>${esc(last.client.name)} — ${last.start}</p><div class="pills" style="margin:1rem 0"><i class="ok">${s.ok} conformes</i><i class="ko">${s.ko} défauts</i><i class="nc">${s.nc} non contrôlés</i></div>
<p style="color:var(--nc)">Le rapport est sauvegardé sur la tablette. Exportez-le au format de votre choix :</p><div class="row" style="justify-content:center;margin-top:1rem">${[['pdf','📄 PDF'],['xls','📊 Excel'],['doc','📝 Word (modifiable)']].map(f=>`<button class="btn" data-a="exp" data-f="${f[0]}" data-id="${last.id}">${f[1]}</button>`).join('')}</div><button class="btn ghost big" data-a="home">Retour à l'accueil</button></section>`}};
const phHTML=()=>draft.steps[draft.step].ph.map((p,k)=>`<div class="ph"><img src="${p.d}"><button data-a="phdel" data-k="${k}">×</button></div>`).join('');
function render(){if(draft)use(draft);const w=view==='wiz',last_=w&&draft.step===STEPS.length-1;
$('#app').innerHTML=`<header><div class="brand"><img class="logoimg" src="logo.png" alt="R.L ENERGIE"><div><b>R.L <em>ENERGIE</em></b><small>Suivi de maintenance</small></div></div><nav>${admin?'<span class="badge">ADMIN</span>':''}${!w&&view!=='done'?`${admin?`<button class="btn" data-a="${view==='adm'?'home':'toadm'}">${view==='adm'?'Accueil':'Gestion'}</button>`:''}<button class="btn" data-a="admin">${admin?'Quitter admin':'🔒 Admin'}</button>`:''}</nav></header><main>${views[view]()}</main>${w?`<div class="nav"><button class="btn ghost" data-a="prev">← Précédent</button><span>${draft.step+1} / ${STEPS.length}</span><button class="btn ok" data-a="next">${last_?'✔ Terminer':'Suivant →'}</button></div>`:''}`}
const goStep=n=>{draft.step=n;saveDraft(1);render();scrollTo(0,0);if(STEPS[n].danger)dlg('<h3 style="color:var(--ko)">⚠ ATTENTION — TRAVAIL SOUS TENSION</h3><p>Vérifiez les consignes de sécurité avant toute intervention.</p><div class="row"><button class="btn ok" data-a="close">J\'ai vérifié — OK</button></div>','danger')};

/* ---------- Actions ---------- */
const A={close,zoom:b=>b.classList.toggle('z'),
ref:b=>{const d=b.dataset.d,c=draft&&view==='wiz'&&STEPS[draft.step].torque;
dlg(d==='et'?`<h3>Étiquettes de sécurité</h3><div class="zoom" data-a="zoom"><img src="docs/etiquettes.jpg" alt="Schéma des étiquettes"></div><p style="color:var(--nc);font-size:.85rem;margin-top:.5rem">Touchez l'image pour zoomer / dézoomer.</p><div class="row"><button class="btn" data-a="close">Fermer</button></div>`
:`<h3>Couples de serrage</h3><div class="tq">${TQREF.map(t=>`<section><h4>${t[0]}</h4><img src="docs/${t[1]}.jpg" alt="">${t[2].map(r=>`<div class="r"><span>${r[0]}</span><b>${r[1]}</b>${c?`<button class="btn sm y" data-a="usetq" data-v="${r[1]}">Utiliser</button>`:''}</div>`).join('')}</section>`).join('')}</div><div class="row"><button class="btn" data-a="close">Fermer</button></div>`,'wide')},
usetq:b=>{draft.steps[draft.step].torque=b.dataset.v;const i=document.querySelector('[data-in="torque"]'),q=$('#tqs');if(i)i.value=b.dataset.v;if(q)q.value=TQ.includes(b.dataset.v)?b.dataset.v:'';saveDraft();close();toast('Couple appliqué : '+b.dataset.v)},
yes:()=>{close();pend&&pend()},home:()=>{view='home';render()},toadm:()=>{view='adm';render()},
admin:()=>admin?(admin=false,view='home',render()):dlg('<h3>Accès administrateur</h3><input id="pwi" type="password" placeholder="Mot de passe"><div class="row"><button class="btn ghost" data-a="close">Annuler</button><button class="btn" data-a="login">Valider</button></div>'),
login:()=>{if(hash($('#pwi').value)===ls.get('rl_pw',hash('admin123'))){admin=true;close();render();toast('Mode administrateur activé')}else toast('Mot de passe incorrect','err')},
pw:()=>dlg('<h3>Nouveau mot de passe</h3><input id="pwn" type="password" placeholder="4 caractères minimum"><div class="row"><button class="btn ghost" data-a="close">Annuler</button><button class="btn" data-a="pwsave">Enregistrer</button></div>'),
pwsave:()=>{const v=$('#pwn').value;if(v.length<4)return toast('Trop court','err');ls.set('rl_pw',hash(v));close();toast('Mot de passe modifié')},
cedit:b=>{editId=b.dataset.id||null;const c=editId?clients.find(x=>x.id==editId):norm({});const f=(k,l,ph='')=>`<label>${l}</label><input id="c_${k}" value="${esc(c[k])}" placeholder="${ph}">`;
dlg(`<h3>${editId?'Modifier':'Nouveau'} client</h3>${f('name','Nom du client / installation *','Ex : Client D - 300 kWc')}${f('address','Adresse / site')}${f('power','Puissance','Ex : 300 kWc')}${f('contact','Contact sur site')}${f('phone','Téléphone')}<label>Dates de maintenance (une par ligne, la plus récente en premier)</label><textarea id="c_dates" rows="3">${esc(c.dates.join('\n'))}</textarea><label>Notes</label><textarea id="c_notes" rows="2">${esc(c.notes)}</textarea><div class="row"><button class="btn ghost" data-a="close">Annuler</button><button class="btn ok" data-a="csave">Enregistrer</button></div>`)},
csave:()=>{const g=k=>$('#c_'+k).value.trim(),name=g('name');if(!name)return toast('Le nom est obligatoire','err');
if(clients.some(c=>c.name.toLowerCase()===name.toLowerCase()&&c.id!=editId))return toast('Ce client existe déjà','err');
const o={name,address:g('address'),power:g('power'),contact:g('contact'),phone:g('phone'),notes:g('notes'),dates:g('dates').split('\n').map(x=>x.trim()).filter(Boolean)};
editId?Object.assign(clients.find(c=>c.id==editId),o):clients.push({id:Date.now(),...o});saveClients();close();render();toast('Client enregistré')},
cdel:b=>ask('Supprimer ce client ? Les rapports déjà enregistrés sont conservés.',()=>{clients=clients.filter(c=>c.id!=b.dataset.id);form.ci='';saveClients();render()}),
delrep:b=>ask('Supprimer définitivement ce rapport ?',()=>{reports=reports.filter(r=>r.id!=b.dataset.id);saveReports();render()}),
start:()=>{if(!form.tech.trim())return toast('Nom du technicien requis','err');if(form.ci==='')return toast('Sélectionnez un client','err');
const P=procs.find(p=>p.id==form.pi&&p.status==='pub')||procs.find(p=>p.status==='pub');if(!P)return toast('Aucune procédure publiée','err');draft=newDraft(clients[form.ci],form.tech.trim(),P);view='wiz';saveDraft(1);render();scrollTo(0,0)},
resume:()=>{view='wiz';use(draft);goStep(draft.step)},dropdraft:()=>ask('Abandonner la maintenance en cours ? Toute la saisie sera perdue.',()=>{draft=null;idb.del('draft');render()}),
st:b=>{const s=draft.steps[draft.step],j=+b.dataset.j;s.st[j]=b.dataset.k;b.parentNode.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));b.closest('.line').classList.remove('miss');saveDraft()},
allok:()=>{const s=draft.steps[draft.step];s.st=s.st.map(()=>'ok');document.querySelectorAll('.line').forEach(l=>{l.classList.remove('miss');l.querySelectorAll('.seg button').forEach(x=>x.classList.toggle('on',x.dataset.k==='ok'))});saveDraft()},
phdel:b=>{draft.steps[draft.step].ph.splice(+b.dataset.k,1);$('#ph').innerHTML=phHTML();saveDraft(1)},
prev:()=>draft.step?goStep(draft.step-1):(view='home',render()),
next:()=>{const i=draft.step,s=draft.steps[i],j=s.st.findIndex(v=>!v);
if(j>=0){toast('Renseignez chaque point de contrôle','err');const e=document.querySelector(`.line[data-j="${j}"]`);e.classList.add('miss');return e.scrollIntoView({block:'center'})}
if(STEPS[i].releve&&(!draft.prod.trim()||!draft.conso.trim()))return toast('Saisissez les deux relevés de compteur','err');
i===STEPS.length-1?finish():goStep(i+1)},
exp:async b=>{const r=reports.find(x=>x.id==b.dataset.id)||last;toast('Génération en cours…');try{const n=fname(r);b.dataset.f==='pdf'?dl(mkPdf(r),n+'.pdf'):b.dataset.f==='xls'?dl(await mkXls(r),n+'.xlsx'):dl(await mkDoc(r),n+'.docx')}catch(e){console.error(e);toast('Erreur : '+e.message,'err')}},
bk:()=>dl(new Blob([JSON.stringify({v:3,clients,reports,procs,docs,plans})],{type:'application/json'}),`Sauvegarde_RL_${today().replace(/\//g,'-')}.json`)};
const A2={tab:b=>{admTab=b.dataset.t;render()},
pedit:b=>{const p=procs.find(x=>x.id==b.dataset.id);pe=p?JSON.parse(JSON.stringify(p)):{id:Date.now(),isNew:1,title:'',desc:'',cat:'',status:'draft',ver:1,docs:[],steps:[{t:'Nouvelle étape',i:[]}]};peR()},
pcancel:()=>{pe=null;close()},sadd:()=>{pe.steps.push({t:'Nouvelle étape',i:[]});peR()},
sdel:b=>{if(pe.steps.length<2)return toast('Une procédure doit garder au moins une étape','err');pe.steps.splice(+b.dataset.k,1);peR()},
smv:b=>{const k=+b.dataset.k,d=+b.dataset.d,a=pe.steps;if(k+d<0||k+d>=a.length)return;[a[k],a[k+d]]=[a[k+d],a[k]];peR()},
psave:()=>{if(!pe.title.trim())return toast('Le titre est obligatoire','err');const bad=pe.steps.findIndex(x=>!(x.t||'').trim());if(bad>=0)return toast(`Étape ${bad+1} : titre manquant`,'err');
pe.steps.forEach(x=>{x.refs=(x.refs||[]).filter(r=>r!=='tq');if(x.torque)x.refs.push('tq');if(!x.refs.length)delete x.refs});
const{isNew,...p}=pe,o=procs.find(x=>x.id===p.id);p.upd=today();o?(p.ver=(o.ver||1)+1,Object.assign(o,p)):procs.push(p);saveProcs();pe=null;close();render();toast('Procédure enregistrée : disponible immédiatement')},
pdup:b=>{const c=JSON.parse(JSON.stringify(procs.find(x=>x.id==b.dataset.id)));c.id=Date.now();c.title+=' (copie)';c.status='draft';c.ver=1;c.upd=today();procs.push(c);saveProcs();render();toast('Procédure dupliquée en brouillon')},
pdel:b=>ask('Supprimer cette procédure ? Les rapports déjà enregistrés sont conservés.',()=>{procs=procs.filter(x=>x.id!=b.dataset.id);saveProcs();render()}),
dedit:b=>{const d=docs.find(x=>x.id===b.dataset.id);de=d?{...d}:{id:'d'+Date.now(),isNew:1,title:'',desc:'',cat:'',type:'image',src:''};deR()},
dcancel:()=>{de=null;close()},
dsave:()=>{if(!de.title.trim())return toast('Le titre est obligatoire','err');if(!de.src)return toast('Choisissez un fichier','err');const{isNew,...d}=de,o=docs.find(x=>x.id===d.id);o?Object.assign(o,d):docs.push(d);saveDocs();de=null;close();render();toast('Document enregistré')},
ddel:b=>ask('Supprimer ce document ? Il disparaîtra des procédures qui l\'utilisent.',()=>{docs=docs.filter(x=>x.id!==b.dataset.id);saveDocs();render()}),
vdoc:b=>{const d=docs.find(x=>x.id===b.dataset.id);if(!d)return;const u=d.type==='pdf'?blobUrl(d.src):'';dlg(`<h3>${esc(d.title)}</h3>${d.desc?`<p class="sdesc">${esc(d.desc)}</p>`:''}<div class="zoom vw"${d.type==='pdf'?'':' data-a="zoom"'}>${d.type==='pdf'?`<iframe src="${u}"></iframe>`:`<img src="${d.src}" alt="">`}</div>${d.type==='pdf'?'':'<p class="hint">Touchez l\'image pour zoomer / dézoomer.</p>'}<div class="row">${u?`<a class="btn ghost" href="${u}" target="_blank" rel="noopener">Ouvrir à part</a>`:''}<button class="btn" data-a="close">Fermer</button></div>`,'wide')}};
Object.assign(A,A2);
const A3={cosave:()=>{const o={};document.querySelectorAll('[data-co]').forEach(i=>o[i.dataset.co]=i.value.trim());ls.set('rl_co',o);toast('Coordonnées enregistrées')},plf:b=>{plf=b.dataset.f;render()},plhf:b=>{plh=b.dataset.f;render()},plcancel:()=>{pl=null;close()},
pledit:b=>{const p=plans.find(x=>x.id==b.dataset.id);pl=p?JSON.parse(JSON.stringify(p)):{id:Date.now(),isNew:1,clientId:'',procId:(procs.find(x=>x.status==='pub')||{}).id,date:nowKey().slice(0,10),time:'08:00',tech:form.tech||'',notes:'',status:'planned',hist:[]};dlg(plHTML())},
plsave:()=>{const p=pl;if(!p.clientId)return toast('Choisissez un client','err');if(!p.date||!p.time)return toast('Date et heure obligatoires','err');const o=plans.find(x=>x.id===p.id),{isNew,why,...d}=p;
if(o){if(o.date!==d.date||o.time!==d.time){(o.hist=o.hist||[]).push({w:today()+' '+z2(new Date().getHours())+':'+z2(new Date().getMinutes()),by:admin?'Admin':(form.tech||'Technicien'),from:o.date+' '+o.time,to:d.date+' '+d.time,why:why||''})}const h=o.hist;Object.assign(o,d,{hist:h,mod:today()})}else{d.hist=[];d.mod=today();plans.push(d)}
savePlans();pl=null;close();render();toast('Planning enregistré')},
pldel:b=>ask('Supprimer cette intervention planifiée ?',()=>{plans=plans.filter(x=>x.id!=b.dataset.id);savePlans();render()}),
plgo:b=>{const p=plans.find(x=>x.id==b.dataset.id),i=clients.findIndex(c=>c.id==p.clientId);if(i<0)return toast('Client introuvable','err');form.ci=String(i);form.pi=p.procId;if(p.tech){form.tech=p.tech;ls.set('rl_tech',p.tech)}A.start();if(draft){draft.planId=p.id;saveDraft(1)}}};
Object.assign(A,A3);
function finish(){draft.end=today();reports.unshift(draft);const c=clients.find(x=>x.id==draft.client.id);if(c&&c.dates[0]!==draft.start)c.dates.unshift(draft.start);
if(draft.planId){const p=plans.find(x=>x.id==draft.planId);if(p){p.status='done';p.reportId=draft.id;p.doneOn=draft.end;savePlans()}}else{plans.push({id:Date.now()+1,clientId:draft.client.id,procId:draft.pid,date:nowKey().slice(0,10),time:nowKey().slice(11),tech:draft.tech,notes:'',status:'done',reportId:draft.id,doneOn:draft.end,unplanned:1,hist:[],mod:today()});savePlans()}saveClients();saveReports();idb.del('draft');last=draft;draft=null;view='done';render();scrollTo(0,0)}

document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(b&&A[b.dataset.a])A[b.dataset.a](b)});
document.addEventListener('input',e=>{const t=e.target,k=t.dataset.in;if(!k)return;
if(k==='tech'){form.tech=t.value;ls.set('rl_tech',t.value)}else if(k==='q')$('#hist').innerHTML=histHTML(t.value);
else if(draft){const s=draft.steps[draft.step];if(k==='obs')s.obs=t.value;else if(k==='torque'){s.torque=t.value;const q=$('#tqs');if(q)q.value=TQ.includes(t.value)?t.value:''}else draft[k]=t.value;saveDraft()}});
document.addEventListener('change',async e=>{const t=e.target,k=t.dataset.ch;if(!k)return;
if(k==='client'){form.ci=t.value;render()}else if(k==='proc'){form.pi=t.value}else if(k==='pp'){ls.set('rl_pp',t.value);toast('Droits mis à jour');render()}else if(k==='dfile'&&t.files[0]){await readDoc(t.files[0]);deR()}
else if(k==='torque'){draft.steps[draft.step].torque=t.value;document.querySelector('[data-in="torque"]').value=t.value;saveDraft()}
else if(k==='photo'){const s=draft.steps[draft.step];for(const f of t.files){const p=await compress(f);p&&s.ph.push(p)}t.value='';$('#ph').innerHTML=phHTML();saveDraft(1)}
else if(k==='restore'&&t.files[0]){try{const d=JSON.parse(await t.files[0].text());(d.clients||[]).forEach((c,n)=>{const x=norm(c,n),o=clients.find(y=>y.name.toLowerCase()===x.name.toLowerCase());o?Object.assign(o,x,{id:o.id}):clients.push(x)});
(d.reports||[]).forEach(r=>{if(!reports.some(x=>x.id===r.id))reports.push(r)});(d.procs||[]).forEach(p=>{if(!procs.some(x=>x.id===p.id))procs.push(p)});(d.docs||[]).forEach(x=>{if(!docs.some(y=>y.id===x.id))docs.push(x)});(d.plans||[]).forEach(p=>{if(!plans.some(x=>x.id===p.id))plans.push(p)});savePlans();saveProcs();saveDocs();reports.sort((a,b)=>b.id-a.id);saveClients();saveReports();render();toast('Sauvegarde restaurée')}catch{toast('Fichier invalide','err')}}});

/* ---------- Exports ---------- */
const rgb=h=>[0,2,4].map(o=>parseInt(h.substr(o,2),16));
function cover(d,r,W,M){const c=CO(),K=[38,40,43],A=[242,169,31],G=[90,94,100],T=(t,x,y,sz,col,b)=>{d.setFont('helvetica',b?'bold':'normal');d.setFontSize(sz);d.setTextColor(...col);d.text(t,x,y)};
d.setFillColor(244,243,238);d.rect(0,0,W,297,'F');d.setFillColor(...A);d.rect(0,0,W,6,'F');
if(LOGOWM){const h=255,w=h*LOGO.w/LOGO.h;d.addImage(LOGOWM,'PNG',(W-w)/2,25,w,h,'rlwm','FAST')}
if(LOGO){const h=60;d.addImage(LOGO.d,'PNG',M,18,h*LOGO.w/LOGO.h,h,'rllogo','FAST')}else{T(c.name,M,44,40,K,1);T(c.tag||'',M,56,13,G)}
d.setFillColor(...A);d.rect(M,112,30,2.5,'F');T('RAPPORT DE MAINTENANCE',M,128,26,K,1);T(r.proc||'Maintenance',M,138,14,G);
d.setFont('helvetica','bold');d.setFontSize(20);d.setTextColor(...K);let y=158;d.splitTextToSize(r.client.name,W-2*M).forEach(t=>{d.text(t,M,y);y+=9});
if(r.client.address){T(r.client.address,M,y,12,G);y+=8}
y=Math.max(y+8,190);[[["Date d'intervention",r.start],['Technicien',r.tech]],[['Puissance',r.client.power||'—'],['Maintenance précédente',r.prev]]].forEach(row=>{row.forEach((p,i)=>{T(p[0].toUpperCase(),M+i*90,y,8,G,1);T(String(p[1]||'—'),M+i*90,y+6,12,K)});y+=18});
d.setFillColor(...K);d.rect(0,247,W,50,'F');d.setFillColor(...A);d.rect(0,247,W,2,'F');
const put=(x,lab,L)=>{L=L.filter(Boolean);if(!L.length)return;T(lab,x,259,8,A,1);d.setFont('helvetica','normal');d.setFontSize(10);d.setTextColor(255,255,255);let q=266;L.forEach(l=>d.splitTextToSize(l,56).forEach(t=>{d.text(t,x,q);q+=5}))};
put(M,'ENTREPRISE',[c.name,c.addr,[c.zip,c.city].filter(Boolean).join(' ')]);put(80,'CONTACT',[c.tel&&'Tél. '+c.tel,c.mail]);put(145,'INFORMATIONS',[c.web,c.siret&&'SIRET '+c.siret])}
function mkPdf(r){const{jsPDF}=window.jspdf,d=new jsPDF({unit:'mm',format:'a4'}),W=210,M=15,NAVY=[17,17,17],s=stats(r);
cover(d,r,W,M);d.addPage();
let y=M;const T=o=>{d.autoTable({theme:'grid',margin:{left:M,right:M,top:M,bottom:18},styles:{fontSize:9.5,cellPadding:2.5,lineColor:[205,213,224],lineWidth:.2,textColor:30},headStyles:{fillColor:NAVY,textColor:255},...o,startY:y});y=d.lastAutoTable.finalY+5};
const H=t=>{if(y>255){d.addPage();y=M}d.setFont('helvetica','bold');d.setFontSize(13);d.setTextColor(...NAVY);d.text(t,M,y+4);y+=8};
H('Informations générales');T({body:[['Client',r.client.name],['Site',r.client.address||'—'],['Puissance',r.client.power||'—'],['Technicien',r.tech],["Date d'intervention",r.start],['Maintenance précédente',r.prev]],columnStyles:{0:{fontStyle:'bold',fillColor:[251,243,213],cellWidth:55}}});
H('Synthèse');T({head:[['Conforme','Défaut constaté','Non contrôlé']],body:[[s.ok,s.ko,s.nc]],styles:{halign:'center',fontSize:12,cellPadding:3}});
H('Défauts constatés');const ko=defects(r);
if(ko.length)T({head:[['Étape','Point','Observation']],body:ko,columnStyles:{0:{cellWidth:50},1:{cellWidth:38}},headStyles:{fillColor:[217,48,37],textColor:255}});else{d.setFont('helvetica','normal');d.setFontSize(10.5);d.setTextColor(30,110,60);d.text('Aucun défaut constaté.',M,y+2);y+=10}
STEPS.forEach((c,i)=>{const p=r.steps[i],L=lines(r,i);if(y>235){d.addPage();y=M}
T({head:[[{content:`${i+1}. ${c.t}`,colSpan:2,styles:{fontSize:11}}],['Point de contrôle','Statut']],body:L.map(l=>[l.d,LBL[l.k]]),columnStyles:{1:{cellWidth:38,halign:'center',fontStyle:'bold'}},
didParseCell:h=>{if(h.section==='body'&&h.column.index===1)h.cell.styles.textColor=rgb(COL[L[h.row.index].k||'nc'])}});y-=2;
T({head:[['Observations']],body:[[p.obs||'RAS']],headStyles:{fillColor:[251,243,213],textColor:[17,17,17]}});
if(p.ph.length){const cw=(W-2*M-5)/2;let rh=0;p.ph.forEach((q,k)=>{if(k%2===0){if(y+72>282){d.addPage();y=M}rh=0}const f=Math.min(cw/q.w,68/q.h),w=q.w*f,h=q.h*f;d.addImage(q.d,'JPEG',M+(k%2)*(cw+5),y,w,h);rh=Math.max(rh,h);if(k%2||k===p.ph.length-1)y+=rh+5})}y+=3});
const n=d.getNumberOfPages();for(let i=2;i<=n;i++){d.setPage(i);d.setFont('helvetica','normal');d.setFontSize(8);d.setTextColor(120);d.setDrawColor(200);d.line(M,285,W-M,285);d.text(`R.L ENERGIE — ${r.client.name} — ${r.start}`,M,290);d.text(`Page ${i-1} / ${n-1}`,W-M,290,{align:'right'})}
return d.output('blob')}

async function mkXls(r){const wb=new ExcelJS.Workbook(),s=stats(r);wb.creator='R.L ENERGIE';
const fill=c=>({type:'pattern',pattern:'solid',fgColor:{argb:'FF'+c}}),bd={style:'thin',color:{argb:'FFCDD5E0'}},B={top:bd,left:bd,bottom:bd,right:bd},hd=(ro)=>ro.eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill=fill('111111');c.border=B;c.alignment={vertical:'middle',horizontal:'center',wrapText:true}});
const y=wb.addWorksheet('Synthèse',{views:[{showGridLines:false}]});y.columns=[{width:34},{width:48}];y.mergeCells('A1:B1');const t=y.getCell('A1');t.value='R.L ENERGIE — Rapport de maintenance';t.font={bold:true,size:16,color:{argb:'FFFFFFFF'}};t.fill=fill('111111');t.alignment={vertical:'middle',indent:1};y.getRow(1).height=34;
[['Client',r.client.name],['Site / adresse',r.client.address||'—'],['Puissance',r.client.power||'—'],['Technicien',r.tech],["Date d'intervention",r.start],['Maintenance précédente',r.prev],['Points conformes',s.ok],['Défauts constatés',s.ko],['Points non contrôlés',s.nc],['Relevé production (kWh)',r.prod||'—'],['Relevé non-consommation (kWh)',r.conso||'—']].forEach((v,k)=>{const ro=y.getRow(3+k);ro.values=v;ro.height=22;ro.eachCell(c=>{c.border=B;c.alignment={vertical:'middle',horizontal:'left',indent:1}});ro.getCell(1).font={bold:true};ro.getCell(1).fill=fill('FBF3D5')});
y.getCell('B9').fill=fill(LIGHT.ok);y.getCell('B10').fill=fill(LIGHT.ko);y.getCell('B11').fill=fill(LIGHT.nc);
const w=wb.addWorksheet('Détail',{views:[{state:'frozen',ySplit:1}],pageSetup:{orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0}});
w.columns=[{header:'N°',width:6},{header:'Étape',width:38},{header:'Point de contrôle',width:46},{header:'Statut',width:16},{header:'Observations',width:60}];hd(w.getRow(1));w.getRow(1).height=26;
let n=2;STEPS.forEach((c,i)=>{const L=lines(r,i),a=n,ob=r.steps[i].obs||'RAS';L.forEach(l=>{const ro=w.addRow([i+1,c.t,l.d,LBL[l.k],ob]);ro.height=24;ro.eachCell(x=>{x.border=B;x.alignment={vertical:'middle',wrapText:true}});ro.getCell(1).alignment={vertical:'middle',horizontal:'center'};
const st=ro.getCell(4);st.fill=fill(LIGHT[l.k||'nc']);st.font={bold:true,color:{argb:'FF'+COL[l.k||'nc']}};st.alignment={vertical:'middle',horizontal:'center'};n++});
if(L.length>1)['A','B','E'].forEach(k=>w.mergeCells(`${k}${a}:${k}${n-1}`))});
const ko=defects(r);if(ko.length){const f=wb.addWorksheet('Défauts');f.columns=[{header:'Étape',width:44},{header:'Point de contrôle',width:44},{header:'Observation',width:60}];hd(f.getRow(1));ko.forEach(v=>{const ro=f.addRow(v);ro.eachCell(c=>{c.border=B;c.alignment={vertical:'middle',wrapText:true}})})}
return new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}

async function mkDoc(r){const D=window.docx,{Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,ShadingType,ImageRun,AlignmentType,Footer,PageNumber}=D,s=stats(r);
const P=(t,o={},p={})=>new Paragraph({...p,children:[new TextRun({text:String(t),font:'Calibri',...o})]});
const C=(t,w,o={})=>new TableCell({width:{size:w,type:WidthType.PERCENTAGE},shading:o.f?{type:ShadingType.CLEAR,fill:o.f,color:'auto'}:undefined,margins:{top:60,bottom:60,left:100,right:100},children:[P(t,o.r||{})]});
const TB=(head,rows,w)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[head&&new TableRow({tableHeader:true,children:head.map((h,k)=>C(h,w[k],{f:'111111',r:{bold:true,color:'FFFFFF'}}))}),...rows.map(x=>new TableRow({children:x.map((c,k)=>C(c.t??c,w[k],c.o||{}))}))].filter(Boolean)});
const H=t=>P(t,{bold:true,size:26,color:'111111'},{spacing:{before:300,after:120}}),u8=d=>Uint8Array.from(atob(d.split(',')[1]),c=>c.charCodeAt(0)),lab=t=>({t,o:{f:'FBF3D5',r:{bold:true}}});
const ch=[LOGO?new Paragraph({spacing:{after:200},children:[new ImageRun({data:u8(LOGO.d),type:'png',transformation:{width:Math.round(130*LOGO.w/LOGO.h),height:130}}),new ImageRun({data:u8(LOGOWM),type:'png',transformation:{width:Math.round(880*LOGO.w/LOGO.h),height:880},floating:{horizontalPosition:{relative:D.HorizontalPositionRelativeFrom.PAGE,offset:Math.round(81*9525)},verticalPosition:{relative:D.VerticalPositionRelativeFrom.PAGE,offset:Math.round(150*9525)},behindDocument:true,allowOverlap:true,wrap:{type:D.TextWrappingType.NONE}}})]}):P('R.L ENERGIE',{bold:true,size:48,color:'111111'}),P('Rapport de maintenance',{size:30,color:'F2A91F',bold:true},{spacing:{after:200}}),...(()=>{const c=CO();return[c.addr,[c.zip,c.city].filter(Boolean).join(' '),c.tel&&'Tél. '+c.tel,c.mail,c.web,c.siret&&'SIRET '+c.siret].filter(Boolean).map(t=>P(t,{size:20,color:'5A5E64'}))})(),
TB(null,[[lab('Client'),r.client.name],[lab('Site'),r.client.address||'—'],[lab('Puissance'),r.client.power||'—'],[lab('Technicien'),r.tech],[lab("Date d'intervention"),r.start],[lab('Maintenance précédente'),r.prev]],[30,70]),
H('Synthèse'),TB(['Conforme','Défaut constaté','Non contrôlé'],[[{t:String(s.ok),o:{r:{bold:true,color:COL.ok}}},{t:String(s.ko),o:{r:{bold:true,color:COL.ko}}},{t:String(s.nc),o:{r:{bold:true,color:COL.nc}}}]],[34,33,33])];
const ko=defects(r);ch.push(H('Défauts constatés'));ko.length?ch.push(TB(['Étape','Point','Observation'],ko,[36,30,34])):ch.push(P('Aucun défaut constaté.',{color:COL.ok}));
STEPS.forEach((c,i)=>{const p=r.steps[i];ch.push(H(`${i+1}. ${c.t}`),TB(['Point de contrôle','Statut'],lines(r,i).map(l=>[l.d,{t:LBL[l.k],o:{f:LIGHT[l.k||'nc'],r:{bold:true,color:COL[l.k||'nc']}}}]),[75,25]),P(''),TB(['Observations'],[[p.obs||'RAS']],[100]));
for(let k=0;k<p.ph.length;k+=2)ch.push(new Paragraph({spacing:{before:120},children:p.ph.slice(k,k+2).map(q=>{const f=Math.min(300/q.w,225/q.h);return new ImageRun({data:u8(q.d),type:'jpg',transformation:{width:Math.round(q.w*f),height:Math.round(q.h*f)}})})}))});
const doc=new Document({sections:[{footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:[`R.L ENERGIE — ${r.client.name} — Page `,PageNumber.CURRENT],size:16,color:'6B7683'})]})]})},children:ch}]});
return Packer.toBlob(doc)}

/* ---------- Démarrage ---------- */
(async()=>{try{reports=(await idb.get('reports'))||[];draft=(await idb.get('draft'))||null;plans=(await idb.get('plans'))||[];procs=(await idb.get('procs'))||[];docs=(await idb.get('docs'))||[];if(!procs.length){procs=[{id:1,title:'Maintenance annuelle',desc:'Procédure standard R.L ENERGIE',cat:'Maintenance',status:'pub',ver:1,upd:today(),docs:[],steps:DEF}];saveProcs()}if(!docs.length&&!(await idb.get('docs_seeded'))){docs=[{id:'d1',title:'Étiquettes de sécurité',desc:"Schéma d'implantation",cat:'Sécurité',type:'image',src:'docs/etiquettes.jpg'}];saveDocs();idb.set('docs_seeded',1)}navigator.storage?.persist?.()}catch(e){console.error(e)}render();})();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
