'use strict';
/* R.L ENERGIE — Démarrage, service worker, raccourcis clavier, sauvegarde en arrière-plan */
/* ---------- Démarrage ---------- */
(async()=>{try{{const lc=ls.get('rl_clients',null),ic=await idb.get('clients');
/* une copie dans localStorage = ancienne version OU écriture de secours : elle fait foi, puis on migre vers IndexedDB */
if(Array.isArray(lc)){clients=lc.map(norm);if(await dbSave('clients',clients)){try{localStorage.removeItem('rl_clients')}catch{}}}
else if(Array.isArray(ic))clients=ic.map(norm)}
reports=(await idb.get('reports'))||[];drafts=(await idb.get('drafts'))||[];ready=1;if(!drafts.length){const old=await idb.get('draft');if(old){drafts=[old];await idb.set('drafts',drafts);await idb.del('draft')}}draft=null;plans=(await idb.get('plans'))||[];procs=(await idb.get('procs'))||[];docs=(await idb.get('docs'))||[];{const c=await idb.get('cats');cats={p:(c&&c.p)||[],d:(c&&c.d)||[]}}{const ps=await idb.get('procs_seeded');if(!procs.length&&!ps){procs=[{id:1,title:'Maintenance annuelle',desc:'Procédure standard R.L ENERGIE',cat:'Maintenance',status:'pub',ver:1,upd:today(),docs:[],steps:DEF}];saveProcs();idb.set('procs_seeded',1)}else if(procs.length&&!ps)idb.set('procs_seeded',1)}if(!docs.length&&!(await idb.get('docs_seeded'))){docs=[{id:'d1',title:'Étiquettes de sécurité',desc:"Schéma d'implantation",cat:'Sécurité',type:'image',src:'docs/etiquettes.jpg'}];saveDocs();idb.set('docs_seeded',1)}navigator.storage?.persist?.();checkSpace()}catch(e){console.error(e)}render();})();
if('serviceWorker' in navigator&&location.protocol.startsWith('http')){const had=!!navigator.serviceWorker.controller;navigator.serviceWorker.register('sw.js').catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(had)toast('Mise à jour installée : elle sera active au prochain démarrage de l\'app')})}
document.addEventListener('keydown',e=>{if(e.key==='Escape')tryClose();else if(e.key==='Enter'){if(e.target.id==='pwi')A.login();else if(e.target.id==='pwn')A.pwsave();else if(e.target.id==='cn')A.catsave();else if(pe&&e.target.dataset&&e.target.dataset.pt!==undefined){e.preventDefault();A.ptadd({dataset:{k:e.target.dataset.k}})}}});
document.addEventListener('click',e=>{if(e.target.classList&&e.target.classList.contains('ov'))tryClose()});
const flush=()=>{if(ready)saveDraft(1)};document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flush()});addEventListener('pagehide',flush);
