/* Lisibilité en plein soleil : contrastes WCAG AA + zones tactiles. Lit le vrai style.css et les couleurs des exports. */
const fs=require('fs'),path=require('path');
const css=fs.readFileSync(path.join(__dirname,'..','style.css'),'utf8'),data=fs.readFileSync(path.join(__dirname,'..','js','data.js'),'utf8');
const V={};[...css.matchAll(/--([a-z0-9]+):(#[0-9a-f]{6})/gi)].forEach(m=>V[m[1]]=m[2]);
const rgb=h=>{h=h.replace('#','');return[0,2,4].map(i=>parseInt(h.slice(i,i+2),16))};
const lin=c=>{c/=255;return c<=.03928?c/12.92:((c+.055)/1.055)**2.4},Lm=c=>{const[r,g,b]=c.map(lin);return .2126*r+.7152*g+.0722*b};
const cr=(a,b)=>{const x=Lm(rgb(a)),y=Lm(rgb(b));return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
let ok=0,ko=0;const t=(n,c)=>{console.log((c?'✅':'❌')+' '+n);c?ok++:ko++};
const chk=(n,f,b,min)=>{const r=cr(f,b);t(`${n} : ${r.toFixed(2)}:1 (min ${min})`,r>=min)};
chk('texte blanc sur vert « Conforme »','#ffffff',V.ok,4.5);
chk('texte blanc sur rouge « Défaut »','#ffffff',V.ko,4.5);
chk('texte blanc sur gris « Non contrôlé »','#ffffff',V.nc,4.5);
chk('texte secondaire gris sur blanc','#'+V.nc.slice(1),'#ffffff',4.5);
chk('texte secondaire gris sur fond crème',V.nc,V.bg,4.5);
chk('texte principal sur fond crème',V.t,V.bg,7);
chk('noir sur jaune (boutons)','#000000',V.y,7);
chk('jaune sur noir (onglet actif)',V.y,V.k,4.5);
chk('bordure des champs / boutons de choix sur blanc (non-texte)',V.bd,'#ffffff',3);
const grab=name=>{const m=data.match(new RegExp(name+'=\\{([^}]*)\\}'))[1];return Object.fromEntries([...m.matchAll(/(\w+):'([0-9A-F]{6})'/g)].map(x=>[x[1],x[2]]))};
const ex=grab('COL'),lt=grab('LIGHT');
for(const k of Object.keys(ex))chk(`impression : statut « ${k} » sur son fond`,'#'+ex[k],'#'+lt[k],4.5);
const minH=(sel,px)=>{const m=css.match(new RegExp(sel.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\{[^}]*?(?:min-)?height:(\\d+)px'));t(`zone tactile ${sel} ≥ ${px} px (${m?m[1]:'?'} px)`,!!m&&+m[1]>=px)};
minH('.btn',48);minH('.btn.sm',44);minH('header .btn',44);minH('.seg button',44);minH('.tab',44);minH('.ph button',44);minH('.chip',40);
console.log(`\n${ok} OK / ${ko} KO`);process.exit(ko?1:0);
