const fs=require('fs'),vm=require('vm'),path=require('path');
const ROOT=path.join(__dirname,'..');
const H={},cs=new Map(),deleted=[];let online=false,fetched=[];
const mk=(u,mode='no-cors')=>({url:'https://x.io/'+u,method:'GET',mode});
const caches={open:async()=>({addAll:async u=>u.forEach(x=>cs.set('https://x.io/'+(x==='./'?'':x),{body:'cached:'+x})),put:async(r,v)=>cs.set(r.url,v)}),
 match:async(r,o)=>{const u=typeof r==='string'?'https://x.io/'+r:r.url;const k=[...cs.keys()].find(x=>o&&o.ignoreSearch?x.split('?')[0]===u.split('?')[0]:x===u);return k?cs.get(k):undefined},
 keys:async()=>['rl-v11','rl-v24'],delete:async k=>{deleted.push(k);return true}};
const self_={location:{origin:'https://x.io'},addEventListener:(t,f)=>H[t]=f,skipWaiting(){},clients:{claim(){}}};
const ctx={self:self_,caches,fetch:async r=>{fetched.push(r.url);if(!online)throw new Error('offline');return{ok:true,type:'basic',clone(){return this},body:'net:'+r.url}},Response:{error:()=>({error:1})},URL};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(ROOT,'sw.js'),'utf8'),Object.assign(ctx,self_,{self:self_}));
const run=async q=>{let out;H.fetch({request:q,respondWith:p=>out=p,waitUntil:p=>p});return out?await out:'IGNORÉ'};
(async()=>{let ok=0,ko=0;const t=(n,c)=>{console.log((c?'✅':'❌')+' '+n);c?ok++:ko++};
 await new Promise(r=>H.install({waitUntil:p=>p.then(r)}));
 const F=fs.readFileSync(path.join(ROOT,'sw.js'),'utf8').match(/F=\[([^\]]*)\]/)[1].split(',').map(x=>x.trim().replace(/'/g,'')).filter(f=>f&&f!=='./');
 t('tous les fichiers listés dans le cache existent sur le disque ('+F.length+')',F.every(f=>fs.existsSync(path.join(ROOT,f))));
 const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),scripts=[...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]);
 t('tout script de index.html est pré-chargé hors ligne',scripts.every(s=>F.includes(s)));
 t('icon-180.png pré-chargé',F.includes('icon-180.png'));
 online=false;
 t('HORS RÉSEAU : js/actions.js servi depuis le cache',(await run(mk('js/actions.js'))).body==='cached:js/actions.js');
 t('HORS RÉSEAU : index.html?x=1 servi',(await run(mk('index.html?x=1','navigate'))).body==='cached:index.html');
 t('HORS RÉSEAU : page inconnue => index.html',(await run(mk('inconnue','navigate'))).body==='cached:index.html');
 t('HORS RÉSEAU : ressource inconnue => erreur propre',(await run(mk('zzz.png'))).error===1);
 online=true;fetched=[];const r=await run(mk('style.css'));
 t('EN LIGNE : réponse immédiate du cache + mise à jour en fond',r.body==='cached:style.css'&&fetched.some(u=>u.endsWith('style.css')));
 await new Promise(r=>setTimeout(r,20));
 t('… le cache reçoit la version réseau',cs.get('https://x.io/style.css').body.startsWith('net:'));
 t('POST et autres origines ignorés',(await run({url:'https://x.io/a',method:'POST',mode:'x'}))==='IGNORÉ'&&(await run({url:'https://autre.com/a',method:'GET',mode:'x'}))==='IGNORÉ');
 await new Promise(r=>H.activate({waitUntil:p=>p.then(r)}));
 t('activation : anciens caches supprimés, version courante gardée',deleted.includes('rl-v11')&&!deleted.includes('rl-v24'));
 console.log(`\n${ok} OK / ${ko} KO`);process.exit(ko?1:0)})();
